# After Consent/Onboarding Steps {#sec-after_onboarding_steps}

## Steps To Complete a Successful Onboarding Session

1. **In Google Calendar, mark the onboarding session as DONE.** When you hit save, be sure to select "Do not send" so they are not notified of the change.

2.  **In Google Calendar, add the One-Week Check-In at the appropriate time, labeled with the participant's subid, e.g: "9999 1 week follow up" **. If it is during a time when you will be taking the call, also assign the visit with your designated color.

3.  **Look in the STAR email account to get the participant's subid**: The email subject is "New Onboarding Form submitted"

4.  **Add the participant's subid to their STAR account **: The email subject is "A new person has signed up for STAR." 
    a. Click the email where it says "View their account". This will open the STAR website.
    b. Enter the user's subID in the text box for "Study ID"
    c. Hit save.

5.  **In the STAR website, send the STAR Welcome Message to the new user via Direct Message**
    
    a. Make sure you are logged in as star@psych.wisc.edu (It should say "STAR Help (M-F 9am - 5pm Central)" in the sidebar menu)
    
    b. Go to Peer Support > Direct Messages. Search for their screenname or subid; hit the + sign to compose the message.

    b. Send the following (including the HTML code around the links - it will render properly once you hit send)
    
    Subject: 
    
    *Welcome to STAR!*
    
    Body of message (be sure to change the follow up visit date and add your name):

```html
Hello, Thank you again for talking with me today and joining our study! Here are some links that might be helpful as you get started.
    
<a target=_blank href=https://starstudy.wisc.edu/>Our website</a>

<a target=_blank href=https://starstudy.wisc.edu/faq/>A list of frequently asked questions about the payment, the app, and the study</a>

<a target=_blank href=https://go.wisc.edu/xz4szi>The link to sign your W-9</a>

<a target=_blank href=https://uwmadison.co1.qualtrics.com/jfe/form/SV_89fOXmASpmTIFEy>The STAR training video survey (this is the same link I texted you)</a>

I'll be calling you again on {INSERT DATE/TIME}. You should receive a letter in the mail from us with your payment card and instructions on how to get paid. As a reminder, you will need to return your W-9 to us before we can issue payment.

You can reply to this message or call (608) 571-3810 if you have any questions before our call.

Thanks again,

<YOUR NAME>

STAR Study Team
```

6.  **In Google Voice, add the participant's phone number to Contacts, with their 4-digit subid as their contact name**:
    a. See instructions [here](google_voice.qmd){target="_blank"}
    
7. **In Google Voice, send the welcome text message**
    a. Send the following text:

```html
Hello, welcome to STAR! This is the STAR Study support line, staffed Mon-Fri 9am to 5pm Central (Chicago) time. You can save this number in your contacts as STAR Study Support and direct any questions about the study or participation to this line.

To get started, please complete your W-9 form here: https://go.wisc.edu/xz4szi . Remember that this will need to be submitted to us before we can issue any payment.

Next, watch a series of training videos explaining key aspects of the STAR app: https://uwmadison.co1.qualtrics.com/jfe/form/SV_89fOXmASpmTIFEy

These videos will take about 35 minutes to complete and can be viewed any time this week. They will be compensated at a rate of $20, which will be issued, if completed, at the time of your follow-up call.

Monthly payments will be made once per month, on EITHER the 15th OR the 30th, depending on your enrollment date. If the payment date falls on a weekend or bank holiday, you will receive payment Monday or the following business day. Please note that payments will be deposited by 5 PM CST on the day of payment.

Below is an image with the detailed payment breakdown summary.

Thank you again,
STAR Study Team
```    


You also need to attach the [payment infographic image](images\monthly_payment_detail_infographic.png){target="_blank"}. This should also be saved on your RA computers' desktop for easy access. 

8. **Post a new thread for the participant in Slack in the risk2_admin channel**    
    a. If there was anything unusual about the call or the participant had any trouble, add that information as a reply to the thread

9.  **Submit a Visit Date Log**

    a.  <https://uwmadison.co1.qualtrics.com/jfe/form/SV_2hPstJohCYbTmKi>{target="_blank"}
    
10. **Submit Session Guide (if you have not already done so)**

    a.  <https://uwmadison.co1.qualtrics.com/jfe/form/SV_5o2UcfCxseFWpcW>{target="_blank"}


## Steps To Complete after UNSUCCESSFUL Onboarding Session

1. If the participant no-shows:
  a. Mark the visit on the calendar with "NS". When you hit save, be sure to select "Do not send" so they are not notified of the change.
  b. Submit a [Visit Date Log](https://uwmadison.co1.qualtrics.com/jfe/form/SV_2hPstJohCYbTmKi){target="_blank"} and indicate it is a no-show visit.
  c. Post in the risk2_training channel that your visit was a no-show. It might be that we have had multiple no-show visits and we don't want to reschedule them.
  d. Send them a text message in Google Voice with the [no show text message](no_show_texts.qmd){target="_blank"}
  
2. If the participant is uninterested or ineligible:
  a. Mark the visit on the calendar with "ineligible" or "no longer interested". When you hit save, be sure to select "Do not send" so they are not notified of the change.
  b. Post in the risk2_training channel that your visit was ineligible or uninterested. It might be that we have had multiple no-show visits and we don't want to reschedule them.
  
3. If the participant needs to reschedule:
  a. Edit the google calendar event to add "R/S" to the title
  b. Text them the following:
  
  ```html
Hello!  

This is {YOUR NAME} with the UW-Madison STAR Study. I just tried to call for your scheduled consent and onboarding session, but I'm afraid I was unable to reach you. Is now still a good time? The call should take about 30 minutes, and you will receive $20 if you choose to participate.
Thank you,
{YOUR NAME},
Star Study Team

#### Follow-Up No-Show Consent Onboarding (Google Voice Text)
```html
I'm sorry today's time didn't work! If you are still interested in participating in the STAR Study, please select a new date and time to complete this phone session at
https://doodle.com/bp/starstudy1/consent-session  
Thank you,
{YOUR NAME},
Star Study Team
```

