# Aurora - Risk2 Consent and Onboarding Script

NEEDS UPDATING

*Italics are script you read to the participant*\
**\[Items in bold brackets are branches or instructions to you\]**\
Items in Black should be said by Aurora\
<span style="color:red">Items in Red should be said by UW Staff

## Connection

\[Once the participant is connected (via phone), greet them, then ascertain they are in a safe and private place to complete the phone-visit before proceeding. Reschedule If needed.\]

## Aurora Screening Call

*Hi, my name is \[name\] and I am a research associate at Advocate Aurora Health. One of your healthcare providers recently spoke to you about participating in a research study through University of Wisconsin-Madison. They communicated to us that you might be interested in learning more about it. Is now a good time to talk about the study?*

*Great! This is a 12-month study for people who are in recovery from opioids. It will involve using an Android smartphone app that was designed to help people in recovery.*

*People who participate in the study will be paid for completing study tasks through the app and for the phone calls they have with study staff. People who complete all study tasks will receive about \$70 a month. The STAR team at UW -- Madison will also pay \$50 a month to people's cell phone providers to help cover their monthly phone bill.*

*Based on what I have shared, are you interested in hearing more about participating in the study?*

**\[If yes, continue\]**

**\[If no, thank and disconnect- no payment\]**

*The next step will be setting up an enrollment appointment to connect you with the UW-Madison STAR study team. Before we schedule that though, I would like to go through some screening questions with you to make sure you are eligible for the study.*

**\[Begin REDCap screening questions, starting with "Do you have an Android smart phone?" \]**

**\[If ineligible, thank and disconnect- no payment\]**

**\[If eligible, schedule onboarding meeting and text the participant the call-in details\]**

### Introduction -- Aurora

*Hi this is \[name\], a research associate at Advocate Aurora Health. Is now still a good time to talk?*

*Great! Today I'm going to provide you more details about a study being conducted by the University of Wisconsin-Madison*

*If after hearing more about the study you want to participate, I will connect you to the STAR team at UW-Madison. Then, a research technician at UW-Madison who will finish your enrollment and make sure you have all the information you need to get started as a participant. The entire process will take about 30 minutes.*

*Are you interested in learning more about the study?*

### <span style="color:red">Introduction -- UW

<span style="color:red">Hi my name is \[name\] and I am calling from the University of Wisconsin-Madison about the STAR study. Is now still a good time to talk?

<span style="color:red">Great! First, I'm going to tell you more about today's session. I'm going to be telling you about our research study and if you are eligible and interested, I will enroll you. The entire process will take about 30 minutes.

### Description of the study

*This is a 12-month study for people who are in recovery from opioids. It will involve using an Android smartphone app that was designed to help people in recovery, but it is not a treatment study, which means we will not be providing any treatment.*

*People in the study will do tasks using the app. These will include filling out short daily surveys, a longer survey once a month, and sharing smartphone data.*

*People who are part of this study need to keep their phone bill paid and need to be consistent about keeping their phone charged.*

*This study will ask people about their experiences with drugs, so it is important that those who take part feel comfortable honestly answering questions about their use of opioids and other drugs.*

*All the information the study collects will be kept entirely anonymous and stored on the University's secure servers, accessible only to members of the study team. A lot of participants ask us, "if I report a lapse, how do I know law enforcement, CPS, or my treatment provider won't find out?" Well, to prevent this, we've obtained a Certificate of Confidentiality, which means we are protected by the National Institute of Health from being forced to share study information with anyone outside the study team".*

*People who participate will be paid for completing daily and month study tasks. People who complete all the study tasks will receive about \$70 a month, and we will also pay \$50 a month to help people cover their monthly phone bill.*

*Participants will also get paid for the phone calls they have with STAR study staff a total of three times during the study. This session counts as one of the phone calls.*

### Aurora Participants Only:

*Participants who are recruited through Advocate Aurora Health will be asked to share the results of any urine drug screens that they complete through Advocate Aurora Health while they are part of the study. Even though Advocate Aurora Health will share this information with the study team, the study team will not share information with participants' healthcare providers at Advocate Aurora Health.*\
*So, based on what I have shared, are you interested in hearing more about participating in the study?*

**\[If yes, continue\]** **\[If no, thank and disconnect. No payment\]**

**Confirm phone OS- UW only**\
*Wonderful! So, before we continue further, I'd just like to just verify that you do have an Android phone and that you have that phone available to you now?*

**\[If no\]**\
*Unfortunately, our app only works on Android phones, which means I will not be able to enroll you at this time. I apologize for the inconvenience but greatly appreciate your interest in our study and hope you have a wonderful day.* **\[no payment given\]**

**\[If yes\]**\
*Ok great! In that case you can sign up for the study if you wish and we can go ahead and continue.*

**Consent**\
*In this part of the visit, I am going to tell you a little bit more about the study and then give you the chance to formally agree to join it.*

*I'm going to send you a link to an online consent form. Sometimes it takes a while to come through so don't worry if you don't see it yet. You won't need it until a little later, and if you have already received it, I'm going to ask that you hold off on opening it for now.*

**Consent Survey Link:**\
UW: <https://uwmadison.co1.qualtrics.com/jfe/form/SV_6zzSu1ddmyfH46G>\
Aurora: INSERT REDCap Link

*Now I am going to tell you about the study goals and about the risks, benefits, and protections associated with being a participant in the study.*

*The goal of this study is to develop a relapse risk-prediction system. In the future, this system could help people in recovery from opioids by giving them real-time updates about their risk of using.*

*So - In this study, \[the STAR team at UW -- Madison\] will be collecting data from people who are in recovery from opioids because they want to identify the feelings, events, and behavior patterns that can lead to using opioids and other drugs.*

*A lot of people in recovery have "slips," where they use opioids but are still committed to recovery. These slips are sometimes called "relapses," "episodes," or "lapses." And while slips may seem to come out of nowhere and take people by surprise, research has found evidence of warning signs like really stressful events, big changes to life circumstances, changes in moods, or being around friends or places that remind people of their past use.*

*So- the goal of the STAR study is trying to find new warning signs. They are looking for warning signs in two different kinds of information.*

*First, they are looking for warning signs in information that people provide about their own experiences -- so these are things like people's moods, experiences of stress, urges to use, and how much people want to avoid using. This type of information will come from daily and monthly surveys that participants fill out.*

*Second, they are looking for warning signs in information that people do not need to tell them about, and that people might not even know about themselves. For example, people's recent messages or where they go could contain a warning sign. People's routines and patterns or changes to their routines and patterns could also contain warning signs. They gather this type of information from smartphone data including phone calls logs, texts, and location.*

*So far, I have given examples of times when people are at greater risk of using opioids, but in this study, they are also looking for positive signs. People tend to do better in recovery when they are happy, have meaningful contact with other people, and when they have healthy habits and routines.*

*For this study to predict future opioid slips, they will need information about when slips have happened. This means that participants in this study will be asked every day if they have used opioids; and when they used the opioids.*

**Aurora Participants Only:**\
*Participants who have been recruited from Advocate Aurora Health will provide even more information about slips by sharing the results of any urine drug screen tests that they take while they are part of our study. Although the treatment providers here Advocate Aurora Health will share this information about slips with the STAR team at UW-Madison, the STAR team will not share anything back with Advocate Aurora Health or anywhere else. In addition, the results of the urine drug screen test we send to the STAR team will not affect your participation in the STAR study.*

*So that is the main purpose of the study. Do you have any questions?*

**\[Answer questions until they have none\]**

*Now I'm going to describe what people are asked to do as participants in our study.*

-   *Participants download the STAR app onto their phone and have to keep that phone paid for and charged.*\
-   *Every day they fill out a short survey that asks how they are doing.*\
-   *Once a month, they fill out a longer survey that asks about their thoughts and experiences in the last month.*

**Aurora Participants Only:** *Participants recruited from here at Advocate Aurora Health also be asked to allow Advocate Aurora Health to share the results of any urine drug screen tests taken at Advocate Aurora Health.*

*Your participation in the STAR study has no effect on your treatment at Advocate Aurora Health. The STAR team will never share any information about your participation or enrollment status with us.*

*I'd also like to tell you more about what we'll be doing with the smartphone data that people share with us. After I tell you about each item I'll pause and ask if you have any questions.*

-   *People will be asked to give the app permission to access their phone data, text messages, and their location data.*\
-   *For phone data, our computer will be able to see the numbers of people you call or message frequently, and the name you have given them in your Contacts, if any. For example, we might see "this participant texted or spoke with 608-555-1234 four times over the last month. This person is saved in their contacts as Joe Smith". We will use this information only to ask you generic questions about whether talking to this person is harmful or helpful to your recovery.*\
-   *For text messages, our computer is able to read only the text of SMS messages you have sent or received. The computer cannot see any images you might send in texts, or any messages sent using other apps like Snapchat or Facebook. The study team cannot see your actual texts in real time; and we cannot "read your messages". Near the end of the study, our computer will sort through the words in the messages to tell us general things about people's messages. For example, "people in this study used the word 'stressed' in their texts much more often before they had a slip" or "this person used the word "happy" more often when talking to a person they told us was helpful to their recovery"*\
-   *For location data, our computer will be able to look through the GPS points recorded by your phone and use those to identify places you have spent time at. For example, the computer might tell us "this person has visited 101 Main Street two times in the last month". We will use this information only to ask you generic questions about whether visiting this location is helpful or harmful to your recovery. We cannot "see where you are" in real-time and won't know anything about these places other than what you choose to tell us. I also want to reassure you that you will be able to delete any phone logs or SMS messages that you don't want us to see, and you will be able to turn off your location sharing if you don't want us to see where you go for a period of time.*

*Participation in the STAR study is totally voluntary. The study lasts up to one year, but you can stop being part of the study at any time. To remain enrolled, people have to complete most tasks, meaning all monthly updates and at least 6 daily updates per week, and share their phone, text message, and location data. If someone is not able to keep up with tasks or does not want to share their data anymore, we will talk with them and may decide to stop their participation early.*

*It is important that you know that any use of opioids or other drugs has no effect on your participation. You can continue to participate regardless of when or how many times you might use opioids or other drugs. It is only important that you honestly report any opioid or drug use when asked about it in the surveys.*

*Next we'll go over study risks and benefits. There are no major risks related to participation in this study. If you decide to participate, the main risk is that someone might see your information who should not.*

*For this reason, we are very careful and have created safeguards regarding how your data is stored and accessed. Protecting your data and privacy is our top priority, and we are overseen by a group at the University of Wisconsin-Madison that exists to protect and help research subjects. With their guidance, we follow careful protocols for storing, using, and sharing any information that could be used to find out who participants are.*

*Some examples of how we will protect your information and reduce the risk that someone might see it:*

-   *We store your contact information like your name and address in a locked location that is separate from the study data.*\
-   *We label study data with an anonymous study id number.*\
-   *When we share results and data with other researchers, we will not share information that could be used to find out who participants are, like their location data.*\
-   *We will only ever give group summaries of demographic information like people's age, gender, and race or ethnicity.*

*There are no direct benefits of taking part in this study. The STAR app that participants use was designed to help people in recovery and might help you, but we are not treatment providers, and this study is not a treatment. Of course, our team does hope that in the future, what we learn in this study will be used to improve treatments for other people in recovery.*

*We will compensate people who participate in the study for as long as they choose to do so. If you decide to enroll, you will earn:*\
+ *\$20 for the first phone visit (that's this visit)*\
+ *\$10 for a phone call in a week to check in about the study*\
+ *\$10 for a phone call at the very end of the study*

*There will be only 3 calls total over the entire 12-month course of the study. This call counts as one of those three calls. To be clear, we will NOT be calling or checking-in on you regularly aside from the surveys you complete in-app.*

*For every task you complete in the app you will earn payments, and you can also earn bonuses for meeting target goals, with payments up to about \$70 per month.*

*Again, we will also pay you an additional \$50 a month to help cover the cost of your monthly phone bill.*

*Compensation will be provided via a payment debit card that we will mail to you after successful download of the STAR app. Once compensated for the completion of your initial calls and training, you will receive payment on your designated date once a month.*

*All of that said, this study was not designed to make money for the research team or anyone else. If you participate in the study and if the research team develops products from this study, you will not receive any profits. It is also important to let you know that one member of the STAR research team partially owns the company that makes the study app, and as such they may financially benefit from this research study.*

*Based on what I have shared, what questions do you have for me? \[Answer questions\]*

*The information I just gave you about the study goals and the risks, benefits, and protections are things that we make sure everyone who is thinking about joining the study hears and understands.*

*The next step of the process is to make a formal decision about whether you want to be part of the study. In a minute, I'll have you click on that link I sent you, which will show you a Consent Form with all the information I just reviewed stated in more technical language. Then you'll be asked if you are ready to decide if you want to participate. If you do, you'll be asked a few questions, and these will take information that we need to pay you and help make sure our study includes different types of people.*

*Then, finally, you'll download the app and set up an account.*

*Now is the time to open that link that I texted you. You should see a document that says "Consent Form" at the top. You can take as much time as you like to read it over and let me know when you are done. I can sit quietly here in case you have any questions. You'll also be able to download a copy of the consent form if you would like to continue now and read over the full document later or save a copy for your records. Alternatively, if you would like to take some time to think about things, I would also be happy to schedule a follow-up call with you later. So would you like to read it now, continue, or get back to us?*

**\[When done\]**\
*Do you have any questions or anything you want me to know?*

**\[Answer their questions or move on if not\]**\
*You now have three options. You can decide to participate, decide not to participate, or you can take more time to make this decision.*

*If I have answered your questions, and you feel you understand the information in the consent form please tap "Continue" and then select "Yes, I am ready to say "yes" or "no" to participating in this study".*

**\[If not ready\]**

*That's understandable and I'm glad you're going to take more time. You should feel free to discuss the consent with anyone if you feel it will benefit you. It's very important for you to be fully informed and not feel pressured before you consent.*

*You can go ahead and download the consent form by tapping the link on the screen that reads "Click here". After you have read and considered them, please don't hesitate to reach out if you have more questions. We can schedule a time window in the next few days for someone from our team to call back and discuss if you still want to participate after you have had time to review the consent form. Does that work for you?*

**\[If no\]**\
*That's okay, we very much appreciate your time and interest in this study. Have a great day!*

**\[Answer any remaining questions and complete the telephone visit. No payment given\]**

**\[If need more time to think about it\]**\
*That's fine, you can text this number (608-571-3810) if you have any additional questions or if you make a decision. Otherwise, I will reach out to you in about one-week to check-in on how the decision making process is going and answer any additional questions that you might have.*

**\[Pick a time window to call, Answer any remaining questions and complete the telephone visit. Then put the follow up call on the star_psych\@wisc.edu google calendar. No payment given\]**

**\[If yes\]**\
*Okay, great. Please type your full legal name into the space provided. This will function as your electronic signature. Once you are done, please pause and let me know.*

**\[Pause\]**

**Consent Qualtrics to Onboarding Qualtrics Transition - Aurora**

***I am now going to connect you with a member of the STAR team who will help you set up your STAR account and walk you through the onboarding process.***

*Before I connect you with the STAR study team member, do you have any additional questions for me?*

*\[answer questions\]*

**Alright great! From this point forward, I and the rest of the Advocate Aurora staff will no longer be involved in your participation. We will never receive any data about you or your participation from the STAR team. If you have any questions or concerns about your participation from this point on, you should direct them to the STAR team. Please stay on the line while I connect you.**

**\[Connect with STAR Staff\]**

<span style="color:red">**\[Bianca and RA say hello, Bianca introduces the participant to RA, Bianca says goodbye\]**

<span style="color:red">*In the next/this form, you'll be asked to provide some contact information and information about your background. On the first page you'll provide your phone number, phone plan provider, and billing zip code. Then, you will be asked to provide an email you would like to use for the STAR app. Next, you'll be asked to provide a mailing address that we will use to send you the payment debit card, and a W-9 form.*

<span style="color:red">*The W-9 form will come with instructions on how to complete it and a pre addressed envelope. We will not be able to send you your first monthly payment until it is returned, so it is crucial you get this back to us. How you do so is up to your discretion--you can either mail it or take a clear picture and send this to our hotline phone number, which we will provide after the call. If you choose to send an image, we can call over the phone to get your SSN.*

<span style="color:red">*We will mostly communicate with you through the study app, but we occasionally use your email address to get in touch with you. Then the final screen page of questions will ask you to select when you started your medication assisted treatment, as well as your race/ethnicity and date of birth.*

<span style="color:red">*When you are ready, please tap continue to be taken to the next survey form and let me know when you have entered your date of birth.*

<span style="color:red">**Onboarding Survey Link:**\
<span style="color:red"><https://uwmadison.co1.qualtrics.com/jfe/form/SV_0jLkHPzJeVXI0IK>

<span style="color:red">*Great! Now we will get the app downloaded on your phone and set up your study account. If you are not currently on WIFI, this app download will use your cellular data. Will that be okay?*

<span style="color:red">*Great! Please tap continue, and the download should start automatically. The app will guide you through set up. You should agree to the permissions the app or your phone asks of you as it is setting up.*

<span style="color:red">*When the app is downloaded, please let me know what you see on the screen*\
<span style="color:red"><https://star.achess.wisc.edu/apps/android/latest.apk>

<span style="color:red">**\[If participant does not see STAR homepage, troubleshoot\]**

<span style="color:red">hat's ok, sometimes participants have trouble loading the download. *\[Ask questions to determine what/where the issue is\]*

<span style="color:red">**\[If it worked, they should see STAR homepage ("Welcome to STAR", "Create your Account")\]**

<span style="color:red">*Great! Once the app is open, please tell me what you see.*

<span style="color:red">*Can you confirm that you see the STAR landing page/ text that reads "Create your account"?*

<span style="color:red">**\[pause\]**

<span style="color:red">*Once you type in the site id (1202), you'll see a brief introduction. On the next page, you will see a form to Create an Account. This form asks for you to provide your First and Last name, your email and to create a unique screen name. You are going to want to pick a username that does not contain your name, as this is the name that others using the app will see when interacting with you on discussion boards or through direct messages. It can be a nickname or something random that comes to mind. You'll also need to create a password at least 8 characters long.*

<span style="color:red">*Once you've created your account, you should receive several access requests. Please tap allow for this and the other four requests for accesses you receive. This access will allow the STAR app to collect the data we are asking of you as part of your participation. If you want, I can walk you through how each permission will be used by the STAR app to collect data.*

<span style="color:red">**\[Only read if participant wants to be walked through some/all permissions\]**

<span style="color:red">*Allow STAR to access your location*

-   <span style="color:red">*This permission will allow STAR to collect your GPS information and collect data for the visited locations survey*\
    *Allow STAR to access your contacts*\
-   <span style="color:red">*This permission allows us to create the social contacts survey and allow you to add contacts to the friends and family section of the star app*\
    *Allow STAR to make or manage phone calls*\
-   <span style="color:red">*This permission will allow you to dial study staff from the app and dial contacts you add to the friends and family section of the app*\
    *Allow STAR to send and view SMS*\
-   <span style="color:red">*This permission will allow us to gather data on you text message logs. Like I said earlier we will never be able to the content of any pictures you send or receive, and we will remove any personal identifiers from your text logs while we do our data analysis*\
-   <span style="color:red">*Stop Optimizing Battery usage -- Please tap Allow*

<span style="color:red">*Do you have any questions about the access STAR will have to your device?*

<span style="color:red">**\[Pause\]**

<span style="color:red">*Today, the STAR app will ask you to complete the daily update. Please try to take the daily update after this call. Tomorrow and every day after, you will be asked to complete the daily update.*

<span style="color:red">*On the third day of your participation, and then once a month when you are on study, you'll be prompted to complete the monthly update.*

<span style="color:red">*Any questions?*

### <span style="color:red">App Guidelines Information

<span style="color:red">*I want to take some time to tell you a bit about the STAR user guidelines. These guidelines were designed to make sure our participants and staff are protected and are treated professionally and with respect.*

<span style="color:red">*Briefly, our guidelines are...*

<span style="color:red">*To always use respectful language on app discussion boards or in communication with study staff,*

<span style="color:red">*To communicate with staff and other STAR participants as you would in a professional work setting,*

<span style="color:red">*And to avoid sharing personal or private information on the public discussion boards.*

<span style="color:red">*Any questions about these guidelines?*

<span style="color:red">*All in-app messages, posts, and phone calls with staff are subject to review by the STAR team, and staff will remove any discussion post, comment, or individual member who does not follow these guidelines. You can find more information about the app guidelines and the review process for violating app guidelines in the Study Information tab in the STAR App.*

### <span style="color:red">Final Steps

<span style="color:red">*The final step of enrolling in the study will be to watch tutorial videos that describe the app's recovery resources and explain how to complete the different study tasks. You can find these video tutorials in a text message I will send to you shortly after we complete this phone call.*

<span style="color:red">*Completing these video tutorials will take about 35 minutes \[3\] and you will be compensated \$20 for your time.*

<span style="color:red">**(Training Video Link: <https://uwmadison.co1.qualtrics.com/jfe/form/SV_89fOXmASpmTIFEy>)**

<span style="color:red">*If you experience any issues either with the video tutorials or completing any of the study tasks, please do not hesitate to email or call us.*

<span style="color:red">*We'll want to call you in one week to see how everything is going with your participation. This will be a very brief call, only about 5 minutes and you'll receive \$10 compensation for its completion.*

<span style="color:red">*So, one week from now will put us at {insert date that is one-week from onboarding session}. Does that sound like it will work for you?*

<span style="color:red">*And would you like to keep the same time or select a new one?*

<span style="color:red">**\[If no, pick another day either before or after 7 days\]**

<span style="color:red">**\[If yes\]**

<span style="color:red">*And would you like to keep the same time or select a new one?*

<span style="color:red">**\[Allow participant to pick a time\]**

<span style="color:red">*Great! The day before the one-week check-in, we'll send you a quick email to remind you of the call.*

<span style="color:red">**To make sure this study can be a resource to as many people as possible, we ask all our participants where they heard about us and some basic information about their recovery process.**

<span style="color:red">*How did you find out about the study?*\
<span style="color:red">*How has the recovery process been for you?* <span style="color:red">*How many times have you tried to be abstinent in your recovery?*

<span style="color:red">*So that is all I have for you today. Do you have any final questions or concerns?*

### <span style="color:red">Thank Participants and End Visit

<span style="color:red">*Wonderful! Well I want to thank you for your cooperation and patience in completing today's consent and onboarding visit. It's because of the commitment of people like you that we are able to do what we do and hopefully help others, and we appreciate you signing on to participate in our study. As a quick reminder, I'm going to give you a call \[describe next session date/ time\]. Otherwise, I hope you have a wonderful day!*

<span style="color:red">*Thank you!*
