# Overview of Research Design and Methods

## Study Procedure Chronology

1. Recruitment.  Participants recruited (e.g., via VA, MAT clinic, craigslist, reddit, or Facebook ads)  
2. Screening. Participants fill out a screening survey; if eligible, they are directed to a Doodle poll to schedule an Onboarding/Consent call
3. Consent and onboarding. Participants are walked though the study procedures and consent form. Once they give consent, they provide demographic information and are assigned a subID, and are walked through installing the app. They are instructed to watch a set of video tutorials to learn to use the STAR app. They are scheduled for a 1-week check in phone call. They are mailed a set of onboarding materials including a payment card.
4. One-week check-in. Enrolled participants meet with study staff after 1 week via video call to troubleshoot any technical issues and otherwise ensure that they have what they need to participate fully. Specifically ask if they have been recording their faces in the daily video check-ins / if that has been comfortable.
5. Monthly payment. Every month participants will be issued a bonus in the form of a reload on a debit card. They will be sent a confirmation of this payment with a summary of the length of their participation, acknowledgement of their scheduled end date, a summary of their compliance over the month, and a statement of the bonus amount being issued.
6. Debriefing. At the end of the study enrollment period, whether this is after one year or earlier (e.g., for participants to discontinue and who we are able to get in touch with) meet briefly with study staff for a debriefing session.
7. Documentation of participant issues & activities. Each participant has an admin thread in the proj-risk2-admin slack channel. Study activities and participant communication are recorded here. Additionally, There is a Web Log (WOG) where issues with participant data are recorded. There is also a Date Log where participant visit dates and changes in study status are documented.

## Subject Selection

1.  Participant who is interested in the study fills out the screening
    form (the link to which will be made available on the [study website](  https://starstudy.wiscweb.wisc.edu/))

    -   [Screening
        Survey](https://uwmadison.co1.qualtrics.com/jfe/form/SV_2sGbJHYyeBkOOUd)
    -   *Note.* If they qualify, they are asked to enter information
        (name, /and contact preference (call, text, or email)

2.  Participants are then redirected to a Doodle bookable calendar to
    schedule consent/onboarding session
    https://doodle.com/mm/990901332/star-study-screening-visit

### Inclusion Criteria for Study Enrollment

1.  Participants must be aged 18 or older

2.  Participants must be able to read, write, and speak in English

3.  Participants must be currently receiving medication for opioid
    addiction within an opioid treatment program (OTP) or office based
    opioid treatment (OBOT) program; OR be enrolled in or have recently
    completed a day treatment program (DTP, also known as a partial
    hospitalization program or PHP:

    -   Participants on MAT must have been enrolled for a minimum of 1
        month and no longer than 12 months at study intake.

    -   Participants must have adhered to their MAT plan over the last
        month (i.e., must have taken monthly medication for two
        consecutive months; must have taken daily medication 'most days'
        or 'every day')

4.  Participants must have an Android smart phone and an active cellular
    plan that they are able and willing to maintain while enrolled in
    the study. They must also be able and willing to use the phone as
    their personal phone for the duration of the study.

### Pre-Screen Survey Items

These questions are about participating in a research study. We are
looking for people 18 years old or older, who are receiving medication
assisted treatment (MAT) from an outpatient treatment program or
doctor's office-based treatment program, or people who are enrolled in
or have recently completed a day treatment program (DTP, also known as a
partial hospitalization program or PHP).

The study involves using a smartphone recovery support app for one year.
You would complete brief daily check-ins and daily and monthly updates,
and meet virtually with study staff twice for about thirty minutes.

Interested participants who qualify to be in the study and complete
study tasks will receive a \$50 per month personal cell phone plan
credit and up to \$70 per month in study task completion bonuses, paid
by check or reloadable debit card.

First, we would like to ask you several questions that determine whether
you might be a good fit for this study. We will ask about your
smartphone usage, about you, and about any medication assisted
treatments you might be taking or day treatment programs you are
enrolled in.

If you prefer to talk to study staff first and then answer these
questions over the phone, you may instead call our study line and leave
a voicemail at 608-262-1362

First we would like to ask you several questions that determine whether
you might be a good fit for this program. We will ask about your
smartphone usage, about you, and about any medication assisted
treatments you might be taking. We estimate this survey will take less
than 5 minutes to complete.

If you prefer to talk to study staff first and then answer these
questions over the phone, you may instead call our study line and leave
a voicemail at 608-262-1362.

Your answers to these questions will be kept strictly confidential. We
will not ask you for any information that might identify you unless you
are eligible and indicate you wish to give us contact information to
participate. This screening survey is voluntary; you can end your
participation at any time by closing the survey.

If we determine that you are not a good fit for this study after
responding to these questions, we will not be able to tell you the
specific reasons why. The computer chooses who might be a good fit.

If you wish to see & answer the questions, please click continue. 
Continue

1.  **Do you have an Android smart phone?** No; Yes. (Inclusion criteria
    = Yes)

2.  **Is your primary cell phone number an internet-based number such as
    Google Voice or Talkatone?** No; Yes. (Inclusion criteria = No)

3.  **Have you had your current phone number for at least 3 months?**
    No; Yes. (Inclusion criteria = Yes)

4.  **Do you have any other cell phones that you use for personal
    purposes? (Not work phones)** No; Yes. (Inclusion criteria = Yes)

5.  **How old are you?** Under 18; 18 or older. (Inclusion criteria = 18
    or older)

6.  **There are a number of forms that you must read and complete during
    the course of the study, and there are video check-ins. Can you read
    and speak fluently in English?** No; Yes. (Inclusion criteria = Yes)

7.  **This study is for people who are receiving medication assisted
    treatment (MAT); or for those who are enrolled in or have recently
    completed a day treatment program; from an outpatient treatment
    program or doctor's office-based treatment program for opioid
    addiction.**

7a. **Are you currently using medication to support your recovery from
opioid addiction (e.g. Suboxone, Methadone, Vivitrol) within a formal
treatment program or doctor's office?** No; Yes. (Will be ineligible if
7b also No)

7b. **Are you currently enrolled in, or have you recently completed, a
day treatment program to support your recovery from opioid addiction
within a formal treatment program or doctor's office?** No; Yes.
(Inclusion Criteria = will be ineligible if 7a also No)

8.  [Display if Q7a is Yes] **Please select the date you began your
    medication assisted treatment:** [Calendar Select] (Inclusion
    Criteria = \<12 months)
9.  [Display if Q7b is Yes] **Please select the date you began your day
    treatment program:** [Calendar Select] (Inclusion Criteria = \<12
    months)
10. [Display if Q7a is Yes] **Do you use a daily medication to support
    your recovery from opioid addiction?** No; Yes.
11. [Display if Q7a is Yes] **Do you use a monthly medication to support
    your recovery from opioid addiction?** No; Yes.
12. [Display if Q10 is Yes] **In the last month, how often have you
    taken your daily medication?** Never; Rarely; Sometimes; Most Days;
    Everyday(Inclusion criteria = Most Days; Everyday)
13. (Display if Q11 is Yes) **In the last month, have you had one dose
    of monthly medication, at least 4 weeks ago?** No; Yes. (Inclusion
    criteria = Yes)

**End Survey Message If Ineligible.** Thank you very much for your time
filling out this survey. We are looking for a very specific type of
person to be in this study, and unfortunately you do not fit the type of
person we are looking for. Please contact your regular medication
assisted treatment clinic for further options.However, you may be able
to participate in the future. If you choose, you can provide your
contact information and we can reach out to you if anything changes that
might make it able for you to participate. If you consent to being
contacted to about re-screening in the future, please check "I consent",
and on the next page you will submit your name and preferred contact
information. This information will be kept confidential and will only be
used for study staff to contact you if you may in the future be able to
participate.

**End Survey Message If Eligible.** Thank you very much for your time
filling out this survey. We are looking for a very specific type of
person to be in this study, and it looks like you may be a good fit.
Next, we would like to contact you to schedule a time to tell you a
little more about the study, to ask a few more questions to verify that
you can be in the study, and to start your study activities if you are
confirmed to be eligible and interested. This screening visit can be
conducted by phone or video meeting, at your preference. If you consent
to being contacted to move forward, please check "I consent", and on the
next page you will submit your name and preferred contact information.
This information will be kept confidential and will only be used for
study staff to contact you about the next steps.

### Criteria for Study Withdrawal

**Missing data/noncompliance with study procedures**

If one or more of the following conditions is met, participants will be
withdrawn from the study with no option of re-enrolling (unless they
have been incarcerated or enrolled in inpatient treatment).

-   **\< 20 complete daily updates in any four-week period;** \> 2
    missing lapse questions among completed daily updates in the same
    period.

-   **Failing to complete a total of three monthly updates**.

-   **Failing to provide location data consistently** by disabling
    location sharing for more than 12 hours in a four-week period.

-   **Failing to provide SMS and phone log data consistently** by
    disabling SMS and phone log sharing for more than 12 hours in a
    four-week period. **NOTE:** We tell participants this but can't
    enforce this criterion b/c STAR does not allow us to record
    SMC/phone call sharing.

-   **Failing to provide SMS content data** by disabling SMS content
    sharing for more than 12 hours in a four-week period. **NOTE:** We
    tell participants this but can't enforce this criterion b/c STAR
    does not allow us to record SMC/phone call sharing.

**Simplified version from Consent form:**

For each month, you must:

-   Complete 20 daily updates without missing questions.

-   Complete 1 monthly update, with less than 5 missing questions. Must
    not miss 3 monthly updates total.

-   Share GPS location data consistently. You must not disable location
    sharing for more than 12 hours in a single month.

-   Share phone log data consistently. You must not disable phone log
    sharing for more than 12 hours in a single month.

-   Share SMS log data consistently. You must not disable SMS log
    sharing for more than 12 hours in a single month. 

Additionally, If a participant becomes incarcerated during their study participation,
no data will be collected during the period of their incarceration, and
they will be considered withdrawn unless they contact us after their
incarceration to re-establish participation.

**Violation of app guidelines**

Participants may be withdrawn if their behavior on the STAR App or in communication with staff violates App Guidelines. Study staff will discuss guideline violations on a case-by-case basis - with John having the final say.