# Payment Frequently Asked Questions

**Q: When will I receive payment?**  
A: Participants will receive payment on their designated date once a month, on either the 15th or 30th as determined by their start date. Payments will always be issued by 5 PM Central Time. If a payment date falls on a weekend or bank holiday, payments will instead by issued the following business day. If you are unsure about your payment date, please contact the STAR team directly.  

**Q: Why are payments always issued by 5 PM Central Time?**  
A: Payments are issued by 5 PM Central Time as our team calculates them manually. We begin the process at 6 AM day of, and then spend the next few hours manually reviewing each and every participant's data to ensure they receive the maximum amount possible.  

**Q: What happens when a payment date is on a weekend or holiday?**  
A: Payments will instead be issued the following business day by 5 PM Central Time.  

**Q: What do I do if my card is lost or stolen?**  
A: Contact US Bank Card Services at 877-474-0010. They can freeze your card and provide a replacement. They also have representatives 24/7!  

**Q: What if I never received my payment card?**  
A: Contact our team with your address and we can provide a replacement. This does not apply if you have already received and activated a payment card from us in the past.  

**Q: How much can I expect to earn?**  
A: Participants may receive up to $120 a month and $1560 over the 12-month course of the study. The precise amount may vary due to the length of each month, for instance, one may be compensated less for February than for March. Specifically, one will earn: $1.25 per daily survey, $10 per monthly survey, and $50 a month towards the payment of cell service if phone log, SMS, and GPS data are shared. Participants will also earn $5 for each type of data shared and up to two $5 bonuses per month if at least 6 daily surveys are completed a week. This comes to about $70 for tasks and bonuses and $50 for the cell phone bill. Participants also receive compensation for the three calls they have with STAR Study Staff, being their initial onboarding session, the one-week follow-up, and a debrief at the end of the study. These are compensated at $20, $10, and $10, respectively.  

**Q: How do I submit my W-9?**  
A: Please fill in the information requested at the secure docusign link. You can find this link in the initial welcome text and DM we sent via STAR.

**Q: What if I don't have a social security number or don't want to share it?**
A: You will need to provide a social security number or employee identification number (EIN) to participate.

**Q: Why do I have to complete a W-9?**  
A: Any earnings over $600 in one tax year must be reported to the IRS, per federal law. Since you stand to earn over the qualifying amount by participating in this research, will not be able to issue payment until your W-9 is received. Please note that this may affect your eligibility for certain benefits and/or the amount of tax you owe.




