# FAQ Daily and Monthly Tasks  

**Q: How can I view my progress calendar?**   
A: Go to the STAR home page and click on the "Today's Progress" bar displayed at the top of your screen.  

**Q: I feel like my progress calendar is incorrect. What should I do?**  
A: Contact the Study Team and let us know what days are inaccurate.  

**Q: What can  I post on the discussion board?**  
A: The discussion board is designed to be a place where participants can support one another and discuss their experiences with recovery. We do NOT allow sharing of any personal information such as phone numbers, email addresses, physical addresses, reddit handles, or full names. We also do not allow bullying or harrassment towards any other participants or staff members. If you have a question about the study, please contact the Study Team directly via DM.  

**I think the app is draining my battery. What should I do?**  
A: You can enable the app's Battery Optimization feature in the following steps: 1) Go to your phone's settings 2) Tap "Apps" 3) Tap "STAR" 4) Tap "Battery" 5) Tap "Optimize Battery Usage" 6) Scroll down and to STAR and tap the toggle to the on position.  

**I missed a daily update. Can I take it later?**  
A: Unfortunately, we are unable to open daily updates once they have closed.  

**How much time do I have to complete surveys?**  
A: Daily updates are available from 5 AM Central Time-5 AM Central Time the following day. You will have approximately 3 weeks to complete a monthly survey once it has opened.  

