# Consent/Onboarding Session-Frequently Asked Questions {#sec-faq_consent_onboarding}


<center>(The purpose of this FAQ is to serve as a useful reference for study staff while they are Consenting/Onboarding participants. Study staff should feel free to add new questions as they are asked by participants)</center>

## General tips if you do not understand the question or do not know the answer:

-   Try restating the question to the participant to make sure you understood them\
-   "I'm afraid I don't know the answer to that question, but I will reach out to my supervisor and get back to you as soon as possible"

**Q: "Can I have my {friend/partner/anyone} here with me?"**

A: Yes! But please be aware that we will be discussing sensitive topics. If you do not feel comfortable in your current environment, let us know and we can reschedule your session.

**Q: "Can a person here with me also enroll in the study?"**

A: They would need to complete their own screener and call session with us.

**Q: "What do you mean by an ongoing cell phone plan?"**

A: By "ongoing cell phone plan", we are talking about a cell phone plan that you or someone else pays monthly to the same cell service provider.

**Q: "What if I don't need the monthly phone bill payment/ don't pay my own phone bill?"**

A: No worries. We will provide the $50 for your phone bill payment regardless and do not track your spending.

**Q: "What will actually happen when I report lapses?"**

A: Reporting a lapse will not affect your participation in any way. The information is stored in our computer, and no one on our team will see it in live time.

**Q: "What if I miss a task?"**

A: It is okay and not unexpected that participants will miss a survey here and there. We ask that participants complete at least 6 daily surveys a week, but we do understand there are circumstances that may prevent this at times.
Once a survey has closed, we will be unable to open it again. Completing surveys regularly is a requirement of the study, and a participant will be removed if this requirement is not met.

**Q: "Who will be looking at my text messages?"**

A: The individuals working on our team will never be able to read your messages. Instead, their contents will be stored in our computer, which will sort through everyone's texts at the end of the study and pull key words, for instance "stress" before reported relapses or "happy" when talking to someone you reported was helpful to your recovery. Any personal contact information will be removed from the data before it is fed into the algorithm.

**Q: "What type of group level characteristics would you use/How would you use my text messages/ what does group level characteristics mean?"**

A: Group level data like the percentage of participants in our study of a certain gender, race, ethnicity, or level of schooling may be included in published reports. Private, personal information such as your name, location, or texts will never be shared with anyone outside of the study team.


**Q: "When would the Certificate of Confidentiality have to be broken?"**

A: If you explicitly communicate via an email, phone visit, or other direct communication that you or others are at risk. Examples of this would include reported child or elder abuse.

**Q: "How would being in this study help me?"**

A: This study is not a treatment and we cannot guarantee that it will serve any benefit to you, though we do hope that what we learn from this research will be useful for other individuals in recovery in the future.


**Q: "Can I delete anything I don't want to share?"**

A: Yes. After completing a call, receiving or sending a text you do not want us to see, simply delete it from your call or SMS logs. You can also turn off your location sharing for a period of time (up to 6 hours) if you do not want us to see where you are going.
Keep in mind we will never see any of this information in live time, and our team will never read your messages.

**Q: "What if I need to change phones will on study?"**

A: That is absolutely no problem, as long as your new phone is an android. Simply send us a message to indicate the change and we will assist you in getting STAR downloaded on your new device.

**Q: "What if my phone dies a lot/ I am often in areas with no service?"**

A: We understand there are circumstances wherein an individual's phone may die or they may not have service to share data. If you anticipate you would not regularly be able to keep your phone on or connected to service, this study may not be a good fit for you.


**Q: Can I tell other people I'm in the study?**

A: You are free to share any information with whomever you feel comfortable, but we will not share any details of your study participation with anyone outside of the study team.

**Q: What if I know someone who may be interested in participating?"**

A: Wonderful! We are still actively recruiting. Please send your friend the link to our online screener survey (https://starstudy.wisc.edu/). If they are eligible, they will be able to schedule a call session with us to get enrolled.

**Q: How/when am I going to get paid?"**

A: Payment will be loaded directly to the debit card we will send to your address. You will receive payment once a month, on either the 15th or 30th depending on your start date.

**Q: How will I receive monthly phone bill payments?"**

A: The $50 for your phone bill payment will be issued directly onto your debit card with the rest of your monthly payment.

**Q: Can you put money directly into my bank account/ issue it a different way?"**

A: Unfortunately, no. We can only provide compensation via the payment debit card we will mail to your address.

**Q: How can I create a new email?**\
A: Instructions for creating a Gmail.\
1. Launch your web browser and in the search bar, type "Gmail.com". What do you see?\
2. If you are logged into a Gmail account already, you will need to log out of all Gmail accounts.\
3. Now what do you see on the screen? Answer: \[if they see a list of their Gmail accounts\].\
4. Tap the "Use another account" button.\
5. \[If they see "Sign in to continue using Gmail"\].\
6. Tap the "Create account" button. Then tap, "For myself" \
7. You should now see a form asking for your first and last name, username, to create a password, then create a password. When you are finished filling out the form. Then tap continue.\
8. On the next page, you will be asked to type in your phone number, a recovery email, your birthdate and your gender. When you are done with the form, please let me know. Tap next.\
9. On the next page, you will be asked to verify your phone number by having google send a code to your phone number. Tap send. When you receive a code, type that into the space provided, then tap verify. On the next page, you will be asked if you want to add your phone number to your account for use across Google services, you can tap either skip or Yes, I'm in. On the next page, you will be asked to agree to Google's Privacy and Terms. When you are ready, tap the "I agree" button. You should be taken to your new email's inbox.\
10. Now, please navigate back to the Qualtrics form.

**Q: How can I view the app that I downloaded on my android phone to find the STAR App?**

A: To see if you have successfully downloaded the STAR app, you can hit settings\>\>apps\>\>see all apps. You can scroll down the list and see if there is an app called "STAR". If you find the app on the list, simply click on it and hit open.\

**Q: If I don't want to be a participate anymore, do I just delete the app on my phone? Does that prevent the research team get my data?**  

A: If you are no longer interested in participating, you should notify the STAR research team and then delete the app. Deleting the STAR app or disabling permissions will prevent us from collecting data from your device.  



