# Focus Blue Mailers {#sec-focus_blue_mailer_setup}


<center>(This SOP is the instructions to fill the mailer envelopes to send to participants so they can get paid)</center>

## Create empty mailing envelopes

All materials to create envelopes will be located in room 187 (Susan's office).

1.  Priority Mail envelope
    -   If out, tell Susan

2.  Self-Addressed Stamp Envelope
    - Get 1 Regular university envelope
      -   If out, tell Susan
    - Put a stamp on the small envelope
      -  Tell Susan when we are down to 10-20 stamps
    - Put a STAR address label in the recipient area of the envelope
      -   If out of address labels: load a sheet of label paper and print to color printer from P:\\studydata\\risk2\\administration\\financial\\STAR Study Return Address Labels.docx
      -   If out of label paper, tell Susan\

3.  Focus Blue cards
    -   Located in the bottom drawer of the blue cabinet

4.  W-9 form, highlighted:
    -   If we are out: <https://www.irs.gov/pub/irs-pdf/fw9.pdf> (print 1, page 1 only, 1-sided) then make photocopies using copier code 72463
    -   W-9 highlighting instructions
        -   Highlight the numbers for items 1, 3, 5, 6
        -   Highlight "Social security number"
        -   Highlight "Signature of U.S. person"
        -   Highlight "date"\

5.  2-Page Disclosure form
    -   Located in room 192
    -   If we are out: P:\\studydata\\risk2\\administration\\financial\\focusblue126784009disclosure.pdf (print 1, then photocopy 2 sided (2-pages front & back total) using copier code 72463 & staple)

6. Recruitment flyers (2)
    -   If out: P:\studydata\risk2\administration\recruitment\UW Letter Size Flyer.pdf (print 2-sided to the color printer on first floor)\


## Prepare weekly mailings to newly added participants

1. Count the new participants from this week by checking the new posts in the risk2_admin Slack channel. Pull 1 pre-made Priority Mailer envelope per person

2. Enter payment card numbers into the Participant Payment Log:
    -   This PC \> Private drive \> studydata \> risk2 \> administration \> financial \> participant_payment_logs \> participant_payment_log_risk3.csv\
    - IMPORTANT NOTE: Be sure NOT to use Excel. Instead use Ron's Editor or Ron's Data Edit (two versions of the same software). Excel messes up the date fields and prevents the R scripts from opening the file. If you don't have either Ron's Editor or Ron's Data Edit on your RA computer, please tell Susan.
    - Highlight the last row, and right click -\> "Add row below" to create a new empty row at the bottom.
    - Type in the subID and date, put $20 under Amount, and type and your initials
    - In the "notes" column, type "card registration/consent payment". I often copy this from another row just to make sure I get it perfect; it has to match exactly for me to use this file with R.
    - Upload Notes is NA or blank
    -   Add cardholder ID, which is the last 10 digits of the number on the front of the Focus Blue envelope (starts with 404, 444, etc)
      -   As you are entering the card numbers, on each Focus Blue envelope AND Priority Mail Envelope, lightly write the participant's initials/subid in the corner, so you can be sure there is no mis-match when they are mailed out.
    -   Save and close the payment log


3. Tell Susan to run the script to register the cards. 

4. Susan will tell you when the file is ready for you to prepare the welcome letters
    -   Open the first payment letter - in P:\\studydata\\risk2\\administration\\financial, named "first_payment_2021_04_21.docx"\
    -   You'll see a message "opening this document will run the following SQL Command". Hit **No** and the document will continue to open.
    -   Click the Mailings Menu tab.
    -   Click Select Recipients -\> use an existing list
    -   Browse to the funds file upload .csv that Susan prepared via script: P:\\studydata\\risk2\\administration\\financial\\participant_payment_logs\\funds_file_uploads
    -   Click Finish & Merge -\> Edit individual documents then hit "all".
    -   You'll usually get a note about an Empty Record, that's normal.
    -   Verify the addresses and names printed correctly for each letter, then print the letters to the First Floor Printer.

5.  Prepare the mailers 
    -   Verify the contents. Each mailer should contain
      -   Stamped small envelope
      - Highlighted W-9 form
      -   2 recruitment flyers\
      -   Focus Blue card envelope
      -   2-page disclosure
    - Add the newly printed Welcome letter, making sure the name matches the subid on the focus blue envelope and priority mail envelope

6. Print postage labels. 
    - Open the upload file at P:\\studydata\\risk2\\administration\\financial\\participant_payment_logs\\funds_file_uploads.
    -   Login to USPS.com  Click'n'Ship at <https://www.usps.com/> : sewanta, password in LastPass
        -   Hit Click'n'Ship
        -   Scroll down to Step 2, Delivery Address (everything above that is pre-populated and needs no edits).
        -   Click Batch Order.
        -   Add the address from the focus blue upload file.
        -   Beneath the address click "Save to my address book" and then "Add to Batch".
        -   Repeat until all labels are entered. Scroll down and click the button "Select service and packaging". A new section will appear - you don't need to make ANY changes. At the bottom click "Add to Cart"
        -   On the next page you can review the order and make changes if needed (like if you double entered someone you'll see that here). If no changes, click Billing Information
        -   On the next page you have to click the box "I hereby authorize the USPS to charge....". Then click the Credit & Debit tab. The lab p-card visa is already pre-populated, you just need to enter 501 for the CVC. Then click Print & Pay\
    -   To print the labels, you have to scroll down and select all the labels using the check boxes, then scroll back up and print. Then print the labels to the first floor printer, 2 per page (no receipt needed).
    -   Cut them out around the dark border line\
    -   Tape them to the Priority Mail envelope in the indicated location - be sure NOT to let any tape cover any part of the large barcode, and the tape MUST go around all of the envelope (no loose edges)
    -   Verify the label name & address against the subid/name on the letter and focus blue card before sealing the Priority Envelope.

## Lost or Returned Card Procedure {#sec-lost-card}

1.  Payment card never made it to the participant, or we got the envelope returned in the mail:
    - Go through the steps listed above to send the participant a new packet
    - Do not create a new row in the Participant payment log. Instead, find the original row and move the OLD card number to the "upload notes" column, along with the date of replacement.
    - Put the new card number in the cardholder ID column
    - Tag Susan in the subid thread that the card is ready to be replaced
2.  Card was lost/stolen/destroyed after activation
    -   Do not send replacement card
    -   In Google Voice, text the participant the US Bank Card Services number (877-474-0010) and let them know they should contact US Bank directly for a replacement
