# R Instructions   
## Update packages in R studio   
There are two ways of updating the packages.
1. Using code 
Use the code here: “update.packages(ask = FALSE)” 
The code above will update all the outdated packages without asking permission for each one. 
2. Click on package and update  

## How to update R and R studio   
* **To update R**:  click on “R” on the menu bar once R is opened>> Check for R Updates >> Type “yes” if you see the question “Do you want to visit CRAN now”? >> Download the most recent version of R.  

* **To update R studio**: This time open R studio and click “Help” on the menu bar on the top of the screen >> Check for Updates >> You will see a message asking you if you’d like to download the most recent version of R if there’s a new version.  

## Run code chunks in r markdown files  

Click on one of the icon on the top of the grey code chunk:   
* **The grey arrow down pointing to a green bar**: run all the code chunks above  
* **The green triangle**: run the code chunk below   

Click on the corresponding icon to execute the code chunks you want. You can find a more detailed list of what each symbol means by clicking the dropdown arrow next to the "Run" button on the top of the manual bar. 

## View the data frame generated by the code  
In the environment on the upper right corner of R studio, you will find a list of data frame generated. Simply click on the name of the data you’d like to access.   

## To know if the code finished runnning  
If there is a red stop sign on the right corner of the console/terminal section located on the bottom panel, the code is NOT done. The sign will disappear once the code is done. If you see a red error message showing up under the console section, take a screenshot of the error and consult Susan. 




