# Monthly Survey {#sec-measures_monthly}
 
## Formatting Notes

**General Formatting**

• Brackets are used to  describe skip and branching logic

• Response options in circles are forced choice, response options in
check boxes are select all that apply

• \< page break \> is used to  denote page breaks in STAR surveys

• Bolding is used to  for emphasis or to  highlight discrepancies (e.g.,
items with timeframes that conflict with the instruction text)

**Instruction Text**

• For surveys with items that are questions, instructions start with
"The next set of questions ask about..."

• For surveys with items that are statements, instructions start with
"Listed below are...." In addition, instructions describe how to  select
responses (e.g., "Select how much you agree with each statement")

• By default, instruction text is on its own page

**Survey Headers**

• Survey headers are texts that are displayed on the top of every page
in a survey and that specify times or qualifiers that apply to  all
questions (e.g., "In the past month...")

• Ellipses end all survey headers

**Item text**

• Parentheses are used to  list examples

• First person is only used in statements (i.e., not questions)

**Response Option Defaults**

-   Response options are in ascending order (e.g., no  -\> Yes, 0 -\> 10,
    None -\> Extreme)

-   Likert scales have 5 response options and use the following options
    for each type of response:

    -   Frequency response options are: Never\> Rarely\> Sometimes\>
        Most of the time\> Always

    -   Quantity response options are: Not at all\> Slightly\>
        Moderately\> Considerably\> Extremely

    -   Agreement scale: Strongly Disagree \> Mildly Disagree \> Equally
        Agree and Disagree \> Mildly Agree \> Strongly Agree \### Daily
        Update (Content) **Instructions**
        
## Content


#### Global Instructions

This is the monthly update. It consists of different surveys that ask
about aspects of your life and your recovery including the people you
talk to  and the places you go, your household, personal support network,
opioid use, other drug use, drug treatment services, life events, and
emotions.

Completing this will take about 20 minutes and you will receive a \$10
payment for completing it.

Please read through all questions carefully and answer them honestly.
All of your responses will be kept completely private.

\< page break \>

The term "opioid" in these surveys refers to  prescription opioids (like
Oxycontin or Vicodin), synthetic opioids (fentanyl), and heroin. Below
is a list of commonly used terms for these substances:

**Oxycodone** (Oxycontin, Percocet, oxy, percs, O.C., rims, tires,
greenies)

**Hydrocodone** (Vicodin, Lortab, Norco, vike, bananas, fluff, hydros)

**Morphine** (Kadian, Duramorph, MS Contin, miss Emma, monkey, white
stuff, M)

**Codeine** (lean, captain Cody, little C, schoolboy)

**Buprenorphine** (Suboxone, Subutex, buse, sobos, strips, oranges)
Hydromorphone (Dilaudid, Exalgo, smack, dillies, footballs, juice)

**Methadone** (Methadose, Dolophine, tootsie roll, red rock, mud, dolls)

**Oxymorphone** (Opana, biscuits, mrs. O, *  bomb, octagon)

**Tramadol** (Ultram, chill pills, trammies, ultras)

**Fentanyl** (Sublimaze, Actiq, apache, goodfella, TNT)

**Heroin** (black tar, black pearl, black, china white, dope, white
lady, smack, snow, speedball)

\< page break \>

When we ask about your use of opioids or other drugs, we often use the
term "**non-medical reasons.**" When you see this term please think
about your use of drugs to  feel intoxicated or high. This includes
taking more of a drug than you were prescribed, taking it more
frequently than prescribed, or using a drug for reasons other than it
was prescribed for.

\< page break \>

#### Demographics

[Instructions:] The next set of questions asks for some general
information about your current life.

\< page break \>

1.  Which of the following have changed in your life in the **past
    month**? Select all that apply.

    -- School enrollment (enrolled, dropped out, or graduated) --
    Employment status (changed jobs or hours, retired, or lost job) --
    Living arrangement (changed where you live or who  you live with) --
    None of the above [if selected, jump to  question 4]

\< page break \>

2.  Are you currently enrolled in school? [Display if "school
    enrollment" selected in Q1]  
    *  No
    *  Yes

\< page break \>

3.  Which of the following categories best describes your employment
    status? [Display if "employment status" selected in Q1]

    *  Employed, working 1-39 hours per week

    *  Employed, working 40 or more hours per week

    *  Not employed, looking for work

    *  Not employed, NOT looking for work

    *  Retired

    *  Disabled, not able to  work

    \< page break \>

4.  Are you currently in a committed romantic relationship?

    *  No  [Skip RAS go  to  WHOASSIST]\
    *  Yes

\< page break \>

5.  What is your current living arrangement? [Display if "living
    arrangement" selected in Q1]

    *  Living alone [Skip to  end of demographic survey]

    *  Living with family/others

    *  Homeless shelter

    *  Homeless unsheltered

    *  Sober living/halfway house

    *  Other

\< page break \>

6.  Who  do  you live with? Select all that apply. [Display if "living
    arrangement" selected in Q1 and "living alone" not selected in Q6]

    -- Spouse/significant other

    -- Child/grandchild

    -- Parent

    -- Other relative

    -- Non-relative

\< page break \>

Do  you live with anyone who...

[Display Q7-Q10 if "living arrangement" selected in Q1 and "living
alone" not selected in Q6]

7.  Uses opioids for medical reasons (uses opioids as prescribed by
    their doctor)?

    *  No   
    *  Yes

8.  Uses opioids for non-medical reasons (uses opioids to  feel
    intoxicated or high)?

    *  No   
    *  Yes

9.  Uses drugs other than opioids for non-medical reasons (do  not
    include tobacco  or alcohol)?

    *  No   
    *  Yes

10. Uses alcohol excessively (very frequently or in large amounts)?

    *  No   
    *  Yes

 \< page break \>

#### Relationship Assessment Scale

[This scale will be skipped by participants who  indicate they are not in
a relationship across Q4 of the monthly demographics survey]

[Instructions:] The next set of questions asks you to  think about your
relationship with your partner in the **past month**.

\< page break \>

In the **past month**...

1.  How satisfied have you been with your relationship?

    Not at all    Mildly    Moderately    Considerably    Extremely

2.  How often have there been problems in your relationship?

    Never    Rarely    Sometimes    Often    Always

3.  How often have you wished you hadn't gotten into this relationship?

    Never    Rarely    Sometimes    Often    Always

\< page break \>

#### Drug Use -- Monthly

[Instructions:] The next set of questions asks about your experience
using drugs for **non-medical** reasons in the **past month**.

\< page break \>

In the **past month**...

1.  Which of the following drugs have you used for non-medical reasons?
    Select all that apply.

    -- Alcohol

    -- Combustible tobacco  products (cigarettes, cigars, cigarillos,
    little cigars, pipe, hookah, bidis)

    -- Electronic cigarettes (e-cigarette, e-vaporizer, vape pen,
    e-hookah, hookah pen)

    -- Opioids (heroin, fentanyl, oxy, etc.)

    -- Cannabis (marijuana, pot, grass, hash, K2, spice, etc.)

    -- Stimulants (cocaine, meth, speed, ecstasy, molly, Adderall, etc.)

    -- Inhalants (nitrous, glue, petrol, paint thinner, etc.)

    -- Sedatives or sleeping pills (Valium, Serepax, Rohypnol, etc.)

    -- Hallucinogens (LSD, acid, mushrooms, PCP, special K, etc.)

    -- None of the above [If selected, skip to  Q5]

\< page break \>

In the **past month**...

2_1. How often have you used alcohol? [display if alcohol is selected in
Q1]

Never Once or twice Weekly Almost daily or daily

3_1. How often have you had a strong desire or urge to  use Alcohol?
[display if alcohol is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_1. Have you failed to  do  what was normally expected of you because of
your use of Alcohol? [display if alcohol is selected in Q1]

*  No

*  Yes

In the **past month**...

2_2. How often have you used Combustible tobacco  products? [display if
Combustible tobacco  products is selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_2. How often have you had a strong desire or urge to  use Combustible
tobacco  products? [display if Combustible tobacco  products is selected
in Q1]

Never Once or twice Weekly Almost daily or daily

4_2. Have you failed to  do  what was normally expected of you because of
your use of Combustible tobacco  products? [display if Combustible
tobacco  products is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_3. How often have you used Electronic cigarettes? [display if
Electronic cigarettes is selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_3. How often have you had a strong desire or urge to  use Electronic
cigarettes? [display if Electronic cigarettes is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_3. Have you failed to  do  what was normally expected of you because of
your use of Electronic cigarettes? [display if Electronic cigarettes is
selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_4. How often have you used Opioids? [display if Opioids is selected in
Q1]

Never Once or twice Weekly Almost daily or daily

3_4. How often have you had a strong desire or urge to  use Opioids?
[display if Opioids is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_4. Have you failed to  do  what was normally expected of you because of
your use of Opioids? [display if Opioids is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_5. How often have you used Cannabis? [display if Cannabis is selected
in Q1]

Never Once or twice Weekly Almost daily or daily

3_5. How often have you had a strong desire or urge to  use Cannabis?
[display if Cannabis is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_5. Have you failed to  do  what was normally expected of you because of
your use of Cannabis? [display if Cannabis is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_6. How often have you used Stimulants? [display if Stimulants is
selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_6. How often have you had a strong desire or urge to  use Stimulants?
[display if Stimulants is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_6. Have you failed to  do  what was normally expected of you because of
your use of Stimulants? [display if Stimulants is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_7. How often have you used Inhalants? [display if Inhalants is
selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_7. How often have you had a strong desire or urge to  use Inhalants?
[display if Inhalants is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_7. Have you failed to  do  what was normally expected of you because of
your use of Inhalants? [display if Inhalants is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_8. How often have you used Sedatives or sleeping pills? [display if
Sedatives or sleeping pills is selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_8. How often have you had a strong desire or urge to  use Sedatives or
sleeping pills? [display if Sedatives or sleeping pills is selected in
Q1]

Never Once or twice Weekly Almost daily or daily

4_8. Have you failed to  do  what was normally expected of you because of
your use of Alcohol? [display if alcohol is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

2_9. How often have you used Hallucinogens? [display if Hallucinogens is
selected in Q1]

Never Once or twice Weekly Almost daily or daily

3_9. How often have you had a strong desire or urge to  use
Hallucinogens? [display if Hallucinogens is selected in Q1]

Never Once or twice Weekly Almost daily or daily

4_9. Have you failed to  do  what was normally expected of you because of
your use of Hallucinogens? [display if alcohol is selected in Q1]

*  No

*  Yes

\< page break \>

In the **past month**...

5.  Which of the following types of opioids have you used? Select all
    that apply. [display if opioids selected in 1]

    -- Fentanyl (Sublimaze, Actiq, apache, goodfella, TNT)

    -- Heroin (black tar, black pearl, black, china white, dope, white
    lady, smack, snow, speedball)

    -- Medication for opioid treatment (e.g., Suboxone, Methadone, etc.)

    -- Prescription opioid not for opioid treatment (OxyContin, Vicodin,
    Percocet, Opana)

6.  How did you take opioids for non-medical reasons? Select all that
    apply. [display if opioids selected in 1]

    -- Oral (swallow, chew) -- Smoke (chase) -- Sniff or snort --
    Injection (IV, muscle, under skin) -- Other \_\_\_\_\_\_\_

7.  Have you overdosed while taking opioids (passed out and/or given
    naloxone, treated by EMT, or went to  a hospital)? [display if
    opioids selected in Q1] *  no  *  1 time *  2 -- 3 times *  4 -- 5 times
    *  More than 5 times

 \< page break \>

#### Medication & Treatment Adherence

[Instructions:] The next set of questions asks about medications,
counseling, or other forms of treatment that you have used to  help your
recovery from opioids in the **past month**.

\< page break \>

1.  What type of medication for opioid use are you currently taking?

    *  Medication taken daily (e.g., Suboxone, Methadone)

    *  Medication taken monthly (e.g., Vivitrol)

    *  I am not taking any medications for opioid use [If selected, skip
    to  Q11 (withdrawal, self-help)]

    *  Medication taken daily (e.g., Suboxone, Methadone) and medication
    taken monthly (e.g., Vivitrol)

\< page break \>

2.  What type of medication will you continue to  take **after this
    month** as your **primary** medication? [Show if "daily and monthly"
    selected in Q1]

    *  Medications that are to  be used daily (e.g., Suboxone, Methadone)

    *  Medications that are to  be used monthly (e.g., Vivitrol)

\< page break \>

3.Which daily medication are you taking? [display if "Daily" selected in
Q1 or Q2]

*  Buprenorphine (Bunavail, Suboxone, Zubsolv, Subutex)

*  Methadone (Methadone Intensol, Methadose, Diskets)

*  Naltrexone (Revia)

*  Other: \_\_\_\_\_

\< page break \>

4.  Which monthly medication are you taking? [Show if "Monthly" selected
    in Q1 or Q2]

    *  Buprenorphine injection (Sublocade)

    *  Naltrexone injection (Vivitrol)

    *  Other: \_\_\_\_\_\_

\< page break \>

5_1. Did you take Buprenorphine injection (Sublocade) in the past month?
[Display if "Buprenorphine injection" selected in Q4]

*  No

*  Yes

5_2. Did you take Naltrexone injection (Vivitrol) in the past month?
[Display if "Naltrexone injection" selected in Q4]

*  No

*  Yes

5_3. Did you take your monthly medication in the past month? [Display if
"Other" selected in Q4]

*  No

*  Yes

\< page break \>

6_1. How often did you take Buprenorphine (Bunavail, Suboxone, Zubsolv,
Subutex) in the past month? [Display if "Buprenorphine" selected in Q3]

Never Rarely Sometimes Most days Every day

6_1. How often did you take Methadone (Methadone Intensol, Methadose,
Diskets) in the past month? [Display if "Methadone" selected in Q3]

Never Rarely Sometimes Most days Every day

6_3. How often did you take Naltrexone (Revia) in the past month?
[Display if "Naltrexone" selected in Q3]

Never Rarely Sometimes Most days Every day

6_4. How often did you take your daily medication in the past month?
[Display if "Other" selected in Q3]

Never Rarely Sometimes Most days Every day

\< page break \>

7.  It can be hard to  take medication for opioid use. What has made it
    hard for you? Select all that apply.

    -- I forget to  take it

    -- I lose my medication

    -- It's to*  expensive/it's not covered under my insurance

    -- Trouble getting it due to  a lack of reliable transportation

    -- I do  not like how the medication makes me feel

    -- The side-effects are unpleasant

    -- I do  not think I need it anymore

    -- I want to  be able to  get high

    -- I do  not like my doctor/clinic/treatment provider

    -- Other\_\_\_\_\_\_

\< page break \>

In the **past month**...

8.  How much have you experienced side-effects while taking your
    medication for opioid use?

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

9.  How effective do  you think your medication for opioid use is? [Skip
    if monthly or daily is not selected in Q1]

    Not at all    Mildly    Moderately    Considerably    Extremely

10. How likely are you to  continue taking your medication for opioid
    use? [Skip if monthly or daily is not selected in Q1]

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **past month**...

11. How much have you experienced opioid withdrawal symptoms?

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **past month**...

12. How often have you attended self-help meetings like AA or NA?

    Never Less than weekly Weekly/near weekly Daily/near daily

\< page break \>

14. How effective do  you think your self-help meetings (NA/AA) are?
    [Skip if Never is selected for Q15]

    Not at all    Mildly    Moderately    Considerably    Extremely

15. How likely are you to  continue attending your self-help meetings
    (NA/AA)? [Skip if Never is selected for Q15]\
    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **past month**...

16. How often have you attended other individual or group counseling
    sessions (not including AA or NA meetings)?

    Never Less than weekly Weekly/near weekly Daily/near daily

\< page break \>

17. How effective do  you think your counseling is? [Skip if Never is
    selected for Q18]

    Not at all    Mildly    Moderately    Considerably    Extremely

18. How likely are you to  continue attending your counseling sessions?
    [Skip if Never is selected for Q18]

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **past month**...

19. Have you taken psychiatric medication for depression, anxiety, or
    other mental health symptoms?

    *  No

    *  Yes

20. Have you attended a detox program or other inpatient residential
    treatment for opioid use(e.g., short or long-term residential
    treatment, hospitalization, rehab)? *  No

    *  Yes

\< page break \>

#### Mid-Survey Message

You are about half-way done with the monthly update! Complete it to
receive a \$10 payment.

\< page break \>

#### Abstinence Confidence/Efficacy Questions

[Instructions:] The next set of questions asks about your recovery goals
over the **past month** and in the **next month**.

\< page break \>

Thinking about the **past month**...

1.  How satisfied are you with your progress toward achieving your
    opioid recovery goals?

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

Thinking forward to  the **next month...**

2.  How motivated are you to  completely avoid using opioids for
    non-medical reasons?

    Not at all    Mildly    Moderately    Considerably    Extremely

3.  How confident are you in your ability to  avoid using opioids for
    non-medical reasons?

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **next month...**

4.  do  you intend to  completely avoid using any other drugs (besides
    opioids)?

    *  No

    *  Yes

\< page break \>

In the **next month...**

5.  Select the drugs below that you are trying to  completely avoid
    using. Select all that apply. [Skip if Never is selected for Q4]

    -- Alcohol

    -- Combustible tobacco  products (cigarettes, cigars, cigarillos,
    little cigars, pipe, hookah, bidis) [If selected; skip to  end of
    survey]

    -- Electronic cigarettes (e-cigarette, e-vaporizer, vape pen,
    e-hookah, hookah pen) [If selected; skip to  end of survey]

    -- Cannabis (marijuana, pot, grass, hash, etc.)

    -- Stimulants (cocaine, meth, speed, ecstasy, molly, Adderall, etc.)

    -- Inhalants (nitrous, glue, petrol, paint thinner, etc.)

    -- Sedatives or sleeping pills (Valium, Serepax, Rohypnol, etc.)

    -- Hallucinogens (LSD, acid, mushrooms, PCP, special K, etc.)

    -- Other \_\_\_\_\_\_\_\_\_\_

\< page break \>

#### Brief Pain Inventory (Short Form, Modified)

[Instructions:] The next set of questions asks about any pain you have
experienced **in the past month**.

\< page break \>

In the **past month...**

1.  How bad has your pain been on average?

    Not at all    Mildly    Moderately    Considerably    Extremely

2.  How much has pain interfered with your enjoyment of life?

    Not at all    Mildly    Moderately    Considerably    Extremely

3.  How much has pain interfered with your general activity?

    Not at all    Mildly    Moderately    Considerably    Extremely

\< page break \>

In the **next month...**

4.  What treatments or medications will you receive for your pain?
    Select all that apply. (Do  not include medication you are receiving
    to  help your opioid recovery efforts)

    -- Opioid pain medications

    -- Non-opioid pain medications

    -- Surgical outpatient procedure (lidocaine injection, steroid
    injection, trigger point injection, medication pump, etc.)

    -- Surgeries (spinal fusion, discectomy, arthroscopic, etc.)

    -- Physical/occupational therapy

    -- Alternative treatments (e.g., massage, yoga, acupuncture,
    meditation, herbal supplements, etc.)

    -- no  treatments or medications

    -- Other

\< page break \>--

#### Behavior and Symptom Identification Scale (BASIS-32)

[Instructions:] Listed on the next page are problems that some people
may experience. Select the response that best describes how much
difficulty you have been having in each problem area. Think about your
experiences in the **past month**.

\< page break \>

In the **past month**, how much difficulty have you had with...

1.  Depression, feeling hopeless

    None at all Mild Moderate Considerable Extreme

2.  Fear, anxiety, or panic\
    None at all Mild Moderate Considerable Extreme

3.  Confusion, loss of memory

None at all Mild Moderate Considerable Extreme

4.  Disturbing thoughts or beliefs\
    None at all Mild Moderate Considerable Extreme

5.  Hearing voices, seeing things

    None at all Mild Moderate Considerable Extreme

\< page break \>

In the **past month**, how much difficulty have you had with...

6.  Manic, bizarre behavior

    None at all Mild Moderate Considerable Extreme

7.  Mood swings, unstable moods

    None at all Mild Moderate Considerable Extreme

8.  Uncontrollable, repetitive behavior (e.g., eating disorder, hand
    washing, hurting yourself)

    None at all Mild Moderate Considerable Extreme

9.  Sexual activity or preoccupation

    None at all Mild Moderate Considerable Extreme

10. Controlling temper, outburst of anger, violence

    None at all Mild Moderate Considerable Extreme

\< page break \>

#### Perceived Stress Scale

[Instructions:] The next set of questions ask about your feelings and
thoughts in the **past month**.

\< page break \>

In the **past month...**

1.  How often have you felt that you were unable to  control the
    important things in your life?

    Never    Rarely    Sometimes    Often    Always

2.  How often have you felt confident about your ability to  handle your
    personal problems?

    Never    Rarely    Sometimes    Often    Always

3.  How often have you felt that things were going your way?

    Never    Rarely    Sometimes    Often    Always

4.  How often have you felt difficulties were piling up s*  high that you
    could not overcome them?

    Never    Rarely    Sometimes    Often    Always

\< page break \>

#### World Health Organization Quality of Life (WHOQOL-BREF 2)

[Instructions:] The next set of questions asks about your quality of
life in the **past month**.

\< page break \>

In the **past month**, how satisfied are you with...

1.  Your overall quality of life

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

2.  Your physical health

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

3.  Your mental health

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

4.  Your sleep

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

\< page break \>

In the **past month**, how satisfied are you with...

5.  Your daily living activities

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

6.  Your capacity for work

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

7.  Yourself

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

8.  Your personal relationships

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

\< page break \>

In the **past month**, how satisfied are you with...

9.  Your sex life

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

10. Your opportunities for leisure activities

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

11. The support you get from your friends

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

12. The conditions of your living place (e.g., your house, apartment)

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

\< page break \>

In the **past month**, how satisfied are you with...

13. The conditions of your neighborhood

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

14. Your access to  health services

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

15. Your access to  transportation

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

16. Your ability to  concentrate

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

17. Your energy for everyday life

    Very dissatisfied Dissatisfied Neither satisfied nor dissatisfied
    Satisfied Very satisfied

\< page break \>

#### Social Connectedness

[Instructions:] The next set of questions asks about social support.
Think about support you have given and received in person or online
(e.g., over email, Facebook, Twitter, etc.) in the **past month**.

\< page break \>

In the **past month,** how often was there someone ...\
1. ...who  you could count on to  listen to  you when you needed to  talk?

    Never       Rarely      Sometimes       Often       Always

2.  ...who  gave you information to  help you understand a situation?

    Never    Rarely    Sometimes    Often    Always

3.  How often did you get support from someone in person (**not** over
    email, Facebook, Twitter, etc.)?

    Never    Rarely    Sometimes    Often    Always

\< page break \> In the **past month,** how often did others ...

4.  . ...count on you to  listen when they needed to  talk?\
    Never    Rarely    Sometimes    Often    Always

5.  . ...get information from you to  help them understand a situation?

    Never    Rarely    Sometimes    Often    Always

6.  How often did you give support to  someone in person (not over email,
    Facebook, Twitter, etc.)?

    Never    Rarely    Sometimes    Often    Always

\< page break \>

#### End of Survey Message {#end-of-survey-message-1}

You have now completed the monthly update! You will receive an
additional \$10 in your next study payment. Thank you!

## Contacts and Location Context Survey

These questions are presented before the rest of the monthly survey, any month that the person has new contacts of locations identified. People can be asked up to  50 locations or contacts in a single survey. If no  new contacts/locations were identified, 

[Instructions:] The first questions ask you about the people you talked
t*  or texted with on your phone over the past month.

Our automated system has identified phone numbers that you interacted
with frequently. The system is not perfect; it may have identified phone
numbers that you do  not recognize. You will be able to  tell us if the
system has made an error.

<page break>

[Display for each phone number identified as a frequent contact for the
month]

You texted or spoke to  a person whose phone number is **\$number**
several times in the past month. Recently, you \$type with them on
$date. This person is saved in your contacts as **$contact_name\*\*.
[Display last sentence only if the number is saved in contacts]

[Repeat context information on every page that asks about this person.]

1.  Which of the following best describes who  this phone number belongs
    to?

    *  Spouse or significant other *  Person I take care of (e.g., my
    child) 
    *  Parent 
    *  Other family member (e.g., grandparent, sibling,
    cousin) 
    *  Friend 
    *  Mental health-related (e.g., a therapist or
    counselor, crisis line) 
    *  Work-related (e.g., a co-worker, my place
    of work) 
    *  Healthcare-related (e.g., a doctor or doctor's office, a
    pharmacy) 
    *  Law-related (e.g., probation or parole officer, legal
    advocate, lawyer) 
    *  Financial-related (e.g., unemployment office,
    bank, debt collector) 
    *  Unknown number [If selected skip to  end of
    survey] 
    *  None of the above [If selected skip to  end of survey]

\< page break \>

You texted or spoke to  a person whose phone number is **\$number**
several times in the past month. Recently, you \$type with them on
$date. This person is saved in your contacts as **$contact_name\*\*.
[Display last sentence only if the number is saved in contacts]

2.  How close are you with the person or people who  you call and/or text
    with at this contact number?

    Not at all    Mildly    Moderately    Considerably    Extremely

3.  In general, how often are calls and/or text messages with this
    contact number pleasant?

    Never Rarely Sometimes Most of the time Always

4.  In general, how often are calls and/or text messages with this
    contact number unpleasant?

    Never Rarely Sometimes Most of the time Always

5.  In general, how much do  calls and/or text messages with this contact
    number help your recovery from opioids?

    Not at all    Mildly    Moderately    Considerably    Extremely

6.  In general, how much do  calls and/or text messages with this contact
    number harm your recovery from opioids?

    Not at all    Mildly    Moderately    Considerably    Extremely

[Instructions:] The next questions ask you about the places you have
gone more than once or spent the night at in the past month.

Our automated system has identified these places using the data you
share with us. The system is not perfect; it may have identified places
that you have not been. You will be able to  tell us if the system has
made an error. <page break>

You visited the place shown below, near \$address, several times in the
past month. Recently, you visited this place on \$date. [display on map,
repeat on every page]

1.  Which of the following best describes this place?

    *  My home [If selected, skip toend of survey]  
    *  Someone else's home  
    *  A shelter, group home, hotel, or other temporary place I stayed [If selected, skip to end of survey]  
    *  A restaurant, business, public place, or other non-residential place  
    *  I do  not recognize this location or was just passing by [If selected, skip to end of survey]

\< page break \>

You visited the place shown below, near \$address, several times in the
past month. Recently, you visited this place on \$date. [display on map]

2.  What do you do at this place? Select all that apply.

    -- Work  
    -- Take classes  
    -- Religious or spiritual activities  
    -- Volunteer or do community service  
    -- Exercise or play sports  
    -- Spend time with friends  
    -- Spend time with family  
    -- Socialize with new people  
    -- Relax  
    -- Drink alcohol  
    -- Get mental health care (e.g., counseling, talk therapy, group therapy, support group)  
    -- Get medication for opioid treatment (e.g., Suboxone, Methadone,
    etc.)  
    -- Get physical health care 
    -- None of the above

\< page break \>

You visited the place shown below, near \$address, several times in the
past month. Recently, you visited this place on \$date. [display on map]

3.  In general, how often is going to this place pleasant?

    Never Rarely Sometimes Most of the time Always

4.  In general, how often is going to this place unpleasant?

    Never Rarely Sometimes Most of the time Always

5.  In general, how much does going to this place help your recovery
    from opioids?

    Not at all    Mildly    Moderately    Considerably    Extremely

6.  In general, how much does going to this place harm your recovery
    from opioids?

    Not at all    Mildly    Moderately    Considerably    Extremely

## Burden Survey

These questions are presented at the end of the monthly survey, at months 3 and 11

[Instructions:] Listed on the next page are statements that describe how
people may feel about their experience with the STAR app and other study
technology over the **past month**. For each statement, select how much
you agree or disagree that the statement describes you.

\< page break \>

Thinking about the **daily update**...

1.  Completing the daily update interfered with my daily activities.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

2.  I disliked completing the daily update.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

3.  Please share any positive or negative comments you have about the
    daily update.

    [Text]

\< page break \>

Thinking about the **daily video  check-in**...

4.  Completing the daily video  check-in interfered with my daily
    activities.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

5.  I disliked completing the daily video check-in.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

6.  Please share any positive or negative comments you have about the
    daily video check-in.

    [Text]

\< page break \>

Thinking about the **monthly update**...

7.  Completing the monthly update interfered with my daily activities.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

8.  I disliked completing the monthly update.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

9.  Please share any positive or negative comments you have about the
    monthly update.

    [Text]

\< page break \>

Thinking about sharing your **GPS location data**...

10. I disliked sharing my GPS location data.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

11. Please share any positive or negative comments you have about
    sharing your GPS location data.

    [Text]

\< page break \>

Thinking about sharing your **phone call logs...**

12. I disliked sharing my phone call logs.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

13. Please share any positive or negative comments you have about
    sharing your phone call logs.

    [Text]

\< page break \>

Thinking about sharing your **SMS logs and message text...**

14. I disliked sharing my SMS logs and message text.

    Strongly disagree    Mildly disagree    Agree and disagree equally    Mildly agree    Strongly agree

15. Please share any positive or negative comments you have about
    sharing your SMS logs and message text.

    [Text]

