# One-Week Staff Check-In {#sec-one_week_script}

The purpose of the One Week Check-In is to check-in with participants on whether they completed the video tutorials, see if they are having any issue completing the study tasks, and what to expect in the coming months (i.e. the social contacts/visited locations survey, the burden questions, and payment)


## 1-week check in overview

During the one week check in, you will:

1. Make sure participants have watched the video tutorials 
2. Ask about issues/concerns with each of the study tasks
3. Provide support for self-regulatory strategies if they are having trouble completing tasks
4. Review GPS/Voice/SMS data collected 
5. Ask if participants phone has been dying more than usual 
6. Inform participants about payment and about the upcoming monthly survey.


## Technology check-in

1. Before the scheduled session, open the `visit_followup.Rmd` script in RStudio.
2. Change the participant subid on line 13
3. Scroll to the bottom of the script and hit the "Run all chunks above" down-arrow where it says "Run everything above here to display data for 1 week checkins".
4. Scroll up to see important information displayed which you will refer to during the call. This may appear in the console area, or it may appear as 4 boxes in the script itself (depending on how your Rstudio is set to display results). You may have to make your RStudio screen wider to display all columns.
  - Participant name and phone number
  - Participant payment date (make note of this!)
  - Compliance data: make note of whether they completed all their daily updates, whether we have more than 10 GPS points, and whether we have any SMS or Voice calls
  - Whether they have completed their training videos and intake survey
  - If they watched the payment videos, whether they wrote down any questions about the videos


## Script

*Hello, this is {insert name} calling from the STAR study. Is this still a good time for you to talk?*

::: {.callout-caution collapse="true"}
## If No
*That's ok! Is there a time that would work for you tomorrow or in the next couple of days? This call should take about 10-15 minutes.* [Find a time that work] *Thank you, we'll call you at that time instead. Goodbye!* [Be sure to add the new visit to the calendar and mark this visit "Rescheduled"]
:::

**{If Yes}**

*Great! I'm calling to check on how the study is going, and how the STAR app is working for you. Now as you may remember at the end of your onboarding session, I sent you a link with several video tutorials that would explain key aspects of the STAR app in detail. Were you able to watch through all of the video tutorials?*

::: {.callout-caution collapse="true"}
## If No

*That's alright. Can I ask why you did not complete the video tutorials?*

**Possible Reasons & responses**

-   **I lost the link to the videos**
    -   *That's ok! Would you like me to send you a new link to the video tutorials at the end of this call? You can still complete the tutorials in the next week to earn an additional \$20 added to your first bonus payment*\
-   **I did not get a chance to watch them/I forgot**
    -   *That's ok! The reason we ask you to watch the video tutorials is because they explain important details about how to set up and use the STAR app. Would you like me to send you a new link to the video tutorials at the end of this call? You can still complete the tutorials in the next week to earn an additional \$20 added to your first bonus payment*
-   **I don't feel like watching them**
    -   *That's ok! The reason we ask you to watch the video tutorials is because they explain important details about how to set up and use the STAR app but as long as you are completing the study tasks, you can still participate in this study. However, you will be missing out on a potential \$20 bonus you would have received if you watched the video tutorials*

:::

**{if yes, refer to the Rscript and see if they had any questions}**\
*Great! Thank you for watching the STAR video tutorials. It looks like you* [DID/DID NOT] *have any questions when you watched them.* [ANSWER THOSE QUESTIONS, IF ANY ]

*Do you have any additional questions about the training materials?* [ANSWER ANY ADDITIONAL QUESTIONS]

*So for watching all of the video tutorials that means that you will receive an additional $20 which I'll have added to your card after this call.*

*Now I wanted to check in and ask how it is going as far as completing each of the study tasks, starting with the monthly update. Were you able to complete the monthly update?*

**(Pause for response)**\
*And how was the monthly update? Did you have any issues?*

**(Pause for response)**\
*Great and how about the daily updates? Any issues with completing the daily update surveys?*

**(Pause for response)**\
*Do you feel like you are able to make the daily update a part of you daily routine?*

::: {.callout-caution collapse="true"}
## If No
*What aspects of the daily study tasks do you feel you are having the most trouble with?*

[Troubleshoot and offer advice if possible. For example, if they say they are having trouble remembering to do the tasks, you might say:]

*Do you have any other daily habits that you could use to remind you to do your study tasks? (for example, if they always eat breakfast at the same time encourage them to do the tasks before or after breakfast;)*

:::

*Next I'd like to review the phone data you are sharing with us.*  [IF NO ISSUES READ:] *It looks like we're getting all the data we need from your phone, so you're all set there.*

IF THERE ARE ISSUES WITH THE DATA

::: {.callout-caution collapse="true"}
## If No or very little GPS

*Unfortunately it looks like we're not getting any GPS from your phone. I can either walk you through making sure that location sharing is enabled, or I can send you instructions by text after our call? *
[Walk them through checking their settings or text this to them afterwards]

* Click the STAR menu
* Click Settings
* Click Research Study Settings
* Click Change Settings
* Click Yes on the warning that comes up. This will open you're phones settings for the STAR App.
* Click Permissions to review what permissions you've granted the STAR App. Make sure that "Location permission" is enabled all the time

[IF THEY SAY THIS IS ALREADY THE CASE, READ:]
*That's okay, it sounds like the problem might be on our end. We'll re-check in a few days and let you know if it's still an issue*

:::

::: {.callout-caution collapse="true"}
## If No SMS AND No Voice
*It also looks like we aren't getting any SMS or Voice logs from your phone. However, this could be because you haven't made any voice calls or sent any SMS, rather than an issue with permissions. If you think you have been making calls or texts, you might want to check those permissions as well.*
:::


*Finally, have you noticed any change in your battery life since download the app? For example, have you noticed it dying more quickly or frequently than usual?*


::: {.callout-caution collapse="true"}
## If Yes
*Ok. It is normal for certain types of cell phones to be more affected by the STARs app location data sharing, especially if you do not use your phone fairly often throughout the day. I can walk you through how to turn on battery optimization for the STAR app, which should improve the issue.*

**{Explain how to turn on battery optimization}**

**1. Go to Settings**\
**2. Tap "Apps"**\
**3. Tap "STAR"**\
**4. Tap "Battery"**\
**5. Tap "Optimize battery usage"**\
**6. Scroll down to STAR and tap the toggle to the On position (the circle should be on the right and the toggle bar should go from gray to blue)**
:::

**{If No}**\
*Great! Well, if it has not impacted your battery life up to this point, it is unlikely that it will negatively impact battery life during the rest of your time on the study. If at any point you start to suspect that your battery life is changing significantly, please reach out to study staff.*


*Now I just want to walk you through what you can expect in the coming weeks and months of your participation in the STAR study. First, you will be receiving your first monthly study payment in the next couple of weeks. This payment will be loaded on the reloadable debit card we sent you. Your first study payment will include payments for all the tasks you've completed and bonuses you've earned*

*Please do not lose or throw away this card. Each month, the bonuses you have earned for completing your study tasks and sharing data the previous month will be added to that card. You will receive your monthly study payments on the* **{15th/30th SPECIFY BASED ON THE R SCRIPT}** *of each month. If that payment date falls on a weekend or bank holiday, you would instead receive payment the following business day.*

*If you do lose or misplace the card, please let us know as soon as possible and we will give you the number for US Bank so they can send you a replacement card*

*Any questions about your study payment?*

*Also, I want to let you know that your next monthly updates will be asking you about the people you talk to (either by text or by phone call) and places you visit over the course of any given month. You will be asked a few questions about each person or place designed to help us understand your relationship to that person or place. Once you have been asked about a person or place, you will not be asked about them again. This means that there may be some months where you are asked about many people or places, and some months where you are asked about very few or no new people or places. As with all the data in this study, any information you provide about the people and places you come into contact with will be kept confidential.*

*Any questions?*

*Additionally, once every few months your monthly update will contain a set of questions that will ask you to report on your experiences as a study participant. These questions are designed to help us understand how people feel about participating in the study and completing the study tasks. Your responses to these questions will be kept confidential and will not affect your study participation in any way.*

*Any questions?*

*Finally, I want to remind you that if you ever have any questions about your participation in the study, the STAR app, or the study itself, you can reach out to us by phone or by email. If we determine that it would be appropriate to set up an appointment to troubleshoot through the issue, you would be compensated for the time you spent.*

*Any questions?*

*Ok then! Well {Insert participant name} I want to thank you for your time today and thank you again for your kindness in volunteering with your study participation.*

## Next Steps

Complete [these steps](after_check_in_steps.qmd) 