# Payment Message Procedure {#sec-payment_messages}


<center>(The purpose of this SOP is to instruct study staff to send monthly payment messages using the STAR Help account)</center>

## Instructions

1.  Go to Files
    -   This PC \> Private drive \> studydata \> risk2 \> administration \> financial \> participant_payment_logs \> payment_messages\
2.  Start at first participant in the payment_messages files from the date you want (either the 15th or 30th)\
3.  Open the participant's document and copy the message that shows up in the Notepad app\
4.  Go to "STAR HELP" admin account (star@psych.wisc.edu username)
    -   Go to Peer Support \> Direct messages \> Plus sign button to start a new message\
5.  Search for participant's username and click the orange paper airplane button\
6.  In the subject line type "Month Year Study Payment"
    -   For example: September 2023 Study Payment\
7.  In the message box, paste the message from the Notepad
    -   Add spacing
    -   Delete the quotation marks around the participant's username
    -   Send the message\
8.  Repeat for all participants from your intended date
