# R Tips {#sec-r_instructions}   
R is a flexible programming language that is used heavily in our lab, both for statistical analysis and also for interacting with our data.

* An R program is called a Script and most of our scripts were written by our PI John Curtin or by Susan.
* We use a GUI called RStudio to write and execute R code. This is already installed on any computer you will be using. 
* You don’t need to know the programming language to use an R script. You just need to click your cursor on a line (or highlight multiple lines) and hit ctrl-Enter (or hit the Run button) to execute the code. 
* The commented lines (usually green, start with #) provide an explanation for what the code is doing.


## R Training resources
If you've never had any programming, R can feel intimidating! We encourage you to work through all of these materials to become more comfortable with R. 

* https://bookdown.org/daniel_dauber_io/r4np_book/ - R for Non-Programmers 
* https://moderndive.netlify.app/1-getting-started.html - Getting Started with Data in R
* https://rladiessydney.org/courses/ryouwithme/01-basicbasics-0/ - RYouWithMe; The BasicBasics
* https://rstudio-education.github.io/hopr/basics.html - Hands-On Programming with R: The Very Basics  
* https://r4ds.had.co.nz/introduction.html - R for Data Science  
* https://rmarkdown.rstudio.com/lesson-1.html - Introduction to RMarkdown 


## Common R-Related Tasks

### Open Github Desktop & Clone or refresh the repo

Our analysis code is kept in what's called a "Github repository". It's called analysis_risk2. The first thing you want to do when you start your shift, is use Github Desktop, make sure analysis_risk2 is the selected repo, and hit the tab that says "Pull Origin". This will download any changes that have been made, so you have the latest version of the code. 

### Open an R project
In order for our scripts to run correctly, you must have the associated project open. In the very upper right-hand corner of R-Studio, just under the window min/max/close controls, you will see a little box icon with "Project: (None)" next to it. Click the down arrow next to that, and hit Open Project. Browse to your repository and you will see a .rProj file that you can open. That opens your project and makes sure that all the scripts can find the right file paths.

If you don't see a .rProj file in the repo, you may need to create one - Ask Susan for guidance!

### Run code chunks in Rmarkdown scripts  

Click on one of the icon on the top of the grey code chunk:   
* **The grey arrow down pointing to a green bar**: run all the code chunks above  
* **The green triangle**: run the code chunk below   

Click on the corresponding icon to execute the code chunks you want. You can find a more detailed list of what each symbol means by clicking the dropdown arrow next to the "Run" button on the top of the manual bar. 

### Running code in the console
You can copy a line or chunk of code and paste it in the console pane (lower left-hand part of Rstudio) and hit enter to run it.

### To know if the code finished runnning  
If there is a red stop sign on the right corner of the console/terminal section located on the bottom panel, the code is NOT done. The sign will disappear once the code is done. If you see a red error message showing up under the console section, take a screenshot of the error and consult Susan. 

### View the data frame generated by the code  
In the "environment" pane (on the upper right corner of R studio), you will find a list of data frame generated. Simply click on the name of the data you’d like to access and it will pop up, looking like a spreadsheet  

### Update packages in R studio   
There are two ways of updating the packages.
1. Using code 
Use the code here: “update.packages(ask = FALSE)” 
The code above will update all the outdated packages without asking permission for each one. 
2. Click on package and update  

### Uupdate R and R studio   
* **To update R**:  click on “R” on the menu bar once R is opened>> Check for R Updates >> Type “yes” if you see the question “Do you want to visit CRAN now”? >> Download the most recent version of R.  

* **To update R studio**: This time open R studio and click “Help” on the menu bar on the top of the screen >> Check for Updates >> You will see a message asking you if you’d like to download the most recent version of R if there’s a new version.  


## Useful Scripts

### visit_followup.Rmd

This script is run before a follow-up visit. It can also be used to open the enrollment database, if you need to look up a participant's email or phone number

To just get the enrollment database, run everything above line 93, then click the enrollment database when it appears in the Environment pane (upper right-hand pane).

### data_report_by_subid.Rmd

This script provides a table of participant data, by day, with columns for completing their daily survey, monthly survey, number of GPS points, SMS messages, and voice messages, and a list of actions they took within the app on that day.

Run everything above line 520 to get the tibble. The first time, it will take a while to load all the dataframes. After that, it goes much more quickly. HOWEVER, you should start each day by clearing your environment and re-running it so it's not using old data.

This script also loads many useful dataframes:

1. all_tokens = can be used to check participant's last login, and whether they are using Chrome
2. chunk 10, dynamic_survey_dates, can be run to get the dates for doing dynamic survey uploads
3. all_training = can be used to check if the participant has completed the training videos
