# Study Recruitment


## Reach out to Orgs that support Opioid Recovery

A detailed outline of our procedure for this form of recruitment can be
found:

A chart of organizations that we reach out to can be found in the RISK2
project_notebook

Starting **November 2021**, we will cold contact organizations that seem
like they work either exclusively or mostly with people in opioid
recovery. These organizations go by several different names. The most
commonly used terms for these organizations are included below:

**Types of Organizations:** Recovery Community Org.; MAT Clinic; Opioid
Treatment Programs; MAT Recovery Support; Recovery Resource
Center/Organization; Sober Homes; Recovery Residence; Recovery Community
Center; Recovery Cafe; Peer Support;

## Aurora Health

-   Clinics around Wisconsin and Illinois

-   Aurora Health will establish initial communication with potential
    participants

-   Their research tech will complete the screening and will walk
    participants through the Consent/Onboarding Qualtrics

-   Once the STAR app is downloaded, the Aurora research tech will
    connect the participant to the STAR research tech to complete the
    onboarding process

Participants who successfully complete either the RedCap Screening
survey or a screening phone call with the Aurora research associate
(Bianca) will be scheduled by the Aurora research associate for a
consent/onboarding session. Participants will be sent a unique RedCap
Consent survey once the Aurora R.A. has established that they are still
eligible.

After they give consent, the Aurora R.A. will call the Star Study Staff. The
Aurora R.A. will leave the call and Star Stuff Staff will send the
participant the Onboarding Qualtrics link via Google Voice. \###




