# Reminder Texts {#sec-reminder_messages}

<center>(This SOP has scripts for reminder texts to send to participants before their calls)</center>



## Read before Sending any Reminders

1. STAR staff will send consent/onboarding session reminders via text the day prior to visits. Staff can use the Google Voice helpline number (the uwmstarstudy\@gmail.com account) for this. 

2. It is VERY important that you verify the number in google voice belongs to the correct person!  
  a.  When you search by Subid, it's best to copy and paste the subid from the calendar invite so you don't transpose digits.
  b.  Make sure the phone number is visible and you can see other texts in their thread! If you search subid 1000 and there's no contact, Google Voice will let you send to 11000 and that's not a real number, so the person does not get the text.  
  c.  If the person is an older participant, they may not have a contact saved. Look them up using the enrollment database and get their number from there.   
  

3. Please include the time in the participant's Time Zone **first**, followed by Central time IF DIFFERENT. For example: 1pm Eastern time/ 12pm Central time. 

4. When you are sending reminders that aren't for tomorrow - for example, if you are sending a Monday visit reminder, on a Friday - PLEASE be sure to change "tomorrow" to the actual day of the visit!

5. Sometimes, when a participant reschedules an onboarding visit, their phone number doesn't copy to the new google calendar event. If you need to send a reminder but there's no phone number, go into the star_psych outlook account and search by name for the original booking, which will have the number.


### How to get time zones:

#### To get time zones for a Consent/Onboard session:

Copy and paste the following code in the Console pane of RStudio; then hit enter to run:
```r
library(tidyverse)
library(here)

path_lab_support <- "../lab_support"
path_data_admin <- "P:/studydata/risk2/data_admin/"

source(here("functions", "fun_star.R"))
source(here(path_lab_support, "fun_gps.R"))

path_admin <- "P:/administration"
token_qualtrics <-
  read_csv(file.path(path_admin, "credentials.csv")) %>%
  filter(resource == "qualtrics") %>%
  pull(token)

screen <- tidy_qualtrics("screening", token_qualtrics,  display_progress = FALSE, raw=TRUE) %>% select(eligible_first_name:LocationLongitude)
```

Click on the "screen" dataframe at the top-right hand side and search by their phone number or email. There's latitude/longitude columns that you can copy & paste into google (put a comma between them) and google will tell you the location zip code and you can use that to check the time zone: ie. 38.946106, -89.417999


#### To verify the time zone of a current participant (1-week or final visit):

Copy & paste the following code in the Console pane of RStudio (hit enter to run):

```r
library(tidyverse)
library(here)

path_lab_support <- "../lab_support"
path_data_admin <- "P:/studydata/risk2/data_admin/"

source(here("functions", "fun_star.R"))
source(here(path_lab_support, "fun_gps.R"))

path_admin <- "P:/administration"
token_qualtrics <-
  read_csv(file.path(path_admin, "credentials.csv")) %>%
  filter(resource == "qualtrics") %>%
  pull(token)
  
enroll <- tidy_qualtrics("enroll", token_qualtrics) #load enrolled
```
Then click the "enroll" dataframe at the top-right hand side and search for the subid. You will see their city/state/zip which you can use to google their time zone.



## Reminder for Consent/Onboarding (Google Voice text)

```html
Hello,  
This is a reminder that you have a consent/onboarding session scheduled for {INSERT TIME} (INSERT TIME ZONE ABBREVIATION)/{INSERT TIME} CENTRAL TIME (CST) Tomorrow (DATE).

The call will come from a number beginning with a 608 area code. It should take around 30 minutes and you will receive $20 if you successfully complete the session.

Please text 'C' to CONFIRM this appointment. If you need to reschedule for any reason, please use the following link: https://doodle.com/bp/starstudy1/consent-session . We thank you for your time and look forward to speaking with you.

{YOUR NAME},
STAR Study Team
```

## Reminder for One-Week Check-In (Google Voice text) 

```html
Hello!
This is a reminder that you have your STAR Study one-week check-in at {INSERT TIME} (INSERT TIME ZONE ABBREVIATION)/{INSERT TIME} CENTRAL TIME (CST), tomorrow, DATE, MONTH DATE. The call should take 5-10 minutes and you'll be compensated $10 for attending. The call will also come from a 608 area code. Please text 'C' to CONFIRM this appointment.

Thank you and I look forward to speaking with you soon!

{YOUR NAME},
STAR Study Team
```

## Reminder for Final Visit (Google Voice text) 

```html
Hello,
This is a reminder that you have a final session scheduled for {INSERT TIME} (INSERT TIME ZONE ABBREVIATION)/{INSERT TIME} CENTRAL TIME (CST) Tomorrow (DATE) .

The call will come from a number beginning with a 608 area code. The call should take less than 30 minutes and you will receive $10 if you successfully complete the session. During the session, our team member will assist you to delete the app or change the permissions to stop data sharing.

Please text 'C' to CONFIRM this appointment. If you need to reschedule for any reason, please let us know by replying to this message.

We thank you for your time and look forward to speaking with you.

{YOUR NAME},
STAR Study Team
```