# Connect to Remote Desktop


<center>(The purpose of this doc is to explain connecting to a remote desktop for staff members)</center>

## For all users:

1.  Install the Wisc VPN, globalprotect on your Mac by following the instructions: <https://kb.wisc.edu/page.php?id=90370>\
2.  Let Susan know if you haven't register a netid that looks like this: "lastname#\_1" (e.g., zpeng59_1)

## Connect using Windows PC:

1.  On the machine you want to connect to: Open by search **"Remote Desktop Settings" \> Enable remote desktop**\

-   For some computers, only the administrator can change the remote desktop settings. If that's the case, login to the "admin" account (see Susan for password) to change the setting.\
-   In Remote Desktop Users, add the account that you want to log into. For example, if you want to log into RA account, type in "RA" in the space "Enter the object names to select"\

2.  On the machine you want to connect to: make sure that the computer is only using LAN and is not using WIFI. You can turn off the WIFI to make sure the machine is using ethernet.\
3.  Go to your laptop/computer: turn on globalprotect and connect with your personal static IP address.\

-   If connected correctly, the assigned local IP address would begin with "146."\
-   You can find your assigned local IP address by clicking on globalprotect portal's **manual bar \> settings \> connection**\

4.  On your laptop/computer: Open by search "Remote desktop connection" and type in the IP address of the remote desktop.\

-   IP address can be found by searching on google: "what is my IP address."\

5.  Sign in with the account\

-   For RAs, use the RA account with password "CurtinLab"

## Troubleshooting on Windows PC

1.  Check firewall settings on machine you want to connect\

-   In **System and Security \> Windows Defender Firewall \> Allow and app or feature through Windows defender Firewall \> Remote desktop** (set to both public and private)\
-   Resource: <https://techgenix.com/remote-desktop-cant-connect-to-the-remote-computer/>

## Connecting using Mac:

1.  Install the Remote Desktop App on your Mac: <https://apps.apple.com/us/app/microsoft-remote-desktop/id1295203466?mt=12>\
2.  Once you have GlobalProtect installed, connect with instructions from <https://kb.wisc.edu/page.php?id=105619>, using one of those static IPs you registered (ie, your lastname_1 and your regular netid password)\

-   Open **Remote Desktop** and connect to your IP address using the same credentials you use to get into your desktop computer. (IP address can be found by searching on google: "what is my IP address.") If it prompts you to use a domain prior to your netid, you might need to try **COMPUTER NAME\\your username**.

## Troubleshooting on Mac:

-   <https://support.apple.com/guide/mac-help/if-your-mac-cant-connect-to-another-computer-mchlp1656/mac>
