# Screening Survey


The screening survey will serve as our recruitment database.

Participants complete a brief screening questionnaire on Qualtrics that
clearly communicates whether people screened in or out. For people who
screen in, they schedule a meeting with us.

After completing the Qualtrics Screening survey, Participants who are
considered eligible will be redirected to the Doodle Bookable calendar (
[https://doodle.com/mm/starstudy/phone-visit)](https://doodle.com/mm/starstudy/phone-visit))

-   Participants select the time block that works best for them
    (10:00am-12:00pm OR 2:00pm-4:00pm)

-   Participants can only select one time block, when they select the
    time block they are asked to give a name, email, and phone number
    (the request for phone number is a custom question)

-   Currently, participants must select an appointment two days in
    advance (minimum notice setting is adjustable)

-   Currently, participants can select appointments up to 3 weeks into
    the future (future horizon setting is adjustable)

**Once a participant selects a time block...**

*Two emails are sent to the participant.*

-   Email confirming the appointment has been booked. It shows as having
    been sent from "STAR study staff"
    (\<[reply-to\@doodle.com](mailto:reply-to@doodle.com)\>). Subject
    line is...

    -   "Confirmation: You've booked a meeting with STAR study staff on
        Doodle Bookable Calendar"

-   A second Email is an invitation to the study phone visit. It shows
    as having been sent from
    [star_psych\@wisc.edu](mailto:star_psych@wisc.edu). Subject line
    is...

    -   "Invitation: STAR Study Phone Visit w/ {Participant Name}\@ Fri
        Mar 26, 2021 Xam - Xpm (EDT) ({Participant Email})

*One email is sent to the study email*

-   When a participant books an appointment, an email is sent to
    star_psych\@wisc.edu email, subject line is...

    -   "{Insert Name} booked a meeting with you on your Doodle Bookable
        Calendar Star Study Phone Visit"

-   Also, when a participant books an appointment, the appointment
    appears on the google calendar for
    [star_psych\@wisc.edu](mailto:star_psych@wisc.edu) . The name of the
    appointment is...

    -   "Star Study Phone Visit w/ {Insert Name)"

\*\*If a participant wants to reschedule an appointment...

-   Participant must open the email from "**STAR study staff"**
    (\<[reply-to\@doodle.com](mailto:reply-to@doodle.com)\>) and click
    on the "Reschedule" button located in the message

Two emails are sent to participant

-   One is a notification of cancellation to the study phone visit. It
    shows as having been sent from
    [star_psych\@wisc.edu](mailto:star_psych@wisc.edu). Subject line
    is...

    -   "Canceled event: STAR Study Phone Visit w/ {Participant Name}\@
        {Previous Appointment Date}, 2021 Xam- Xpm (EDT) ({Participant
        Email})

-   One confirming the NEW appointment has been book. It shows as having
    been sent from "**STAR study staff"**
    (\<[reply-to\@doodle.com](mailto:reply-to@doodle.com)\>). Subject
    line is...

    -   "Confirmation: You've booked a meeting with STAR study staff on
        Doodle Bookable Calendar"

One email is sent to the study email.

-   When a participant reschedules an appointment, an email is sent to
    star_psych\@wisc.edu email, subject line is...

    -   "{Insert Name} rescheduled the meeting with you on your Doodle"

-   Also, when a participant books an appointment, the New appointment
    appears on the google calendar for
    [star_psych\@wisc.edu](mailto:star_psych@wisc.edu) . The name of the
    appointment is...

    -   "Star Study Phone Visit w/ {Insert Name)"

-   NOTE. The old appointment disappears from the calendar

## Screening Survey Questions



These questions are about participating in a research study. We are
looking for people 18 years old or older, who are receiving medication
assisted treatment (MAT) from an outpatient treatment program or
doctor's office-based treatment program, or people who are enrolled in
or have recently completed a day treatment program (DTP, also known as a
partial hospitalization program or PHP).

The study involves using a smartphone recovery support app for one year.
You would complete brief daily check-ins and daily and monthly updates,
and meet virtually with study staff twice for about thirty minutes.

Interested participants who qualify to be in the study and complete
study tasks will receive a \$50 per month personal cell phone plan
credit and up to \$70 per month in study task completion bonuses, paid
by check or reloadable debit card.

First, we would like to ask you several questions that determine whether
you might be a good fit for this study. We will ask about your
smartphone usage, about you, and about any medication assisted
treatments you might be taking or day treatment programs you are
enrolled in.

If you prefer to talk to study staff first and then answer these
questions over the phone, you may instead call our study line and leave
a voicemail at 608-262-1362

First we would like to ask you several questions that determine whether
you might be a good fit for this program. We will ask about your
smartphone usage, about you, and about any medication assisted
treatments you might be taking. We estimate this survey will take less
than 5 minutes to complete.

If you prefer to talk to study staff first and then answer these
questions over the phone, you may instead call our study line and leave
a voicemail at 608-262-1362.

Your answers to these questions will be kept strictly confidential. We
will not ask you for any information that might identify you unless you
are eligible and indicate you wish to give us contact information to
participate. This screening survey is voluntary; you can end your
participation at any time by closing the survey.

If we determine that you are not a good fit for this study after
responding to these questions, we will not be able to tell you the
specific reasons why. The computer chooses who might be a good fit.

If you wish to see & answer the questions, please click continue. 
Continue

1.  **Do you have an Android smart phone?** No; Yes. (Inclusion criteria
    = Yes)

2.  **Is your primary cell phone number an internet-based number such as
    Google Voice or Talkatone?** No; Yes. (Inclusion criteria = No)

3.  **Have you had your current phone number for at least 3 months?**
    No; Yes. (Inclusion criteria = Yes)

4.  **Do you have any other cell phones that you use for personal
    purposes? (Not work phones)** No; Yes. (Inclusion criteria = Yes)

5.  **How old are you?** Under 18; 18 or older. (Inclusion criteria = 18
    or older)

6.  **There are a number of forms that you must read and complete during
    the course of the study, and there are video check-ins. Can you read
    and speak fluently in English?** No; Yes. (Inclusion criteria = Yes)

7.  **This study is for people who are receiving medication assisted
    treatment (MAT); or for those who are enrolled in or have recently
    completed a day treatment program; from an outpatient treatment
    program or doctor's office-based treatment program for opioid
    addiction.**

7a. **Are you currently using medication to support your recovery from
opioid addiction (e.g. Suboxone, Methadone, Vivitrol) within a formal
treatment program or doctor's office?** No; Yes. (Will be ineligible if
7b also No)

7b. **Are you currently enrolled in, or have you recently completed, a
day treatment program to support your recovery from opioid addiction
within a formal treatment program or doctor's office?** No; Yes.
(Inclusion Criteria = will be ineligible if 7a also No)

8.  [Display if Q7a is Yes] **Please select the date you began your
    medication assisted treatment:** [Calendar Select] (Inclusion
    Criteria = \<12 months)
9.  [Display if Q7b is Yes] **Please select the date you began your day
    treatment program:** [Calendar Select] (Inclusion Criteria = \<12
    months)
10. [Display if Q7a is Yes] **Do you use a daily medication to support
    your recovery from opioid addiction?** No; Yes.
11. [Display if Q7a is Yes] **Do you use a monthly medication to support
    your recovery from opioid addiction?** No; Yes.
12. [Display if Q10 is Yes] **In the last month, how often have you
    taken your daily medication?** Never; Rarely; Sometimes; Most Days;
    Everyday(Inclusion criteria = Most Days; Everyday)
13. (Display if Q11 is Yes) **In the last month, have you had one dose
    of monthly medication, at least 4 weeks ago?** No; Yes. (Inclusion
    criteria = Yes)

**End Survey Message If Ineligible.** Thank you very much for your time
filling out this survey. We are looking for a very specific type of
person to be in this study, and unfortunately you do not fit the type of
person we are looking for. Please contact your regular medication
assisted treatment clinic for further options.However, you may be able
to participate in the future. If you choose, you can provide your
contact information and we can reach out to you if anything changes that
might make it able for you to participate. If you consent to being
contacted to about re-screening in the future, please check "I consent",
and on the next page you will submit your name and preferred contact
information. This information will be kept confidential and will only be
used for study staff to contact you if you may in the future be able to
participate.

**End Survey Message If Eligible.** Thank you very much for your time
filling out this survey. We are looking for a very specific type of
person to be in this study, and it looks like you may be a good fit.
Next, we would like to contact you to schedule a time to tell you a
little more about the study, to ask a few more questions to verify that
you can be in the study, and to start your study activities if you are
confirmed to be eligible and interested. This screening visit can be
conducted by phone or video meeting, at your preference. If you consent
to being contacted to move forward, please check "I consent", and on the
next page you will submit your name and preferred contact information.
This information will be kept confidential and will only be used for
study staff to contact you about the next steps.