
# STAR App Features and Content

==List All Features and add short blurb==

## Members

## Settings
**High Risk Locations** - 
Users can add “High Risk Locations” for places that they think may be harmful to their recovery. Adding a high-risk location sets up an alert from Star that will go off when they are at the location. 

**Lock Screen Settings** - 
Users can set, change, or delete a lock screen pin for STAR. If you add create a PIN, you will need to type in that PIN when you open STAR after it has been closed for several minutes. 

To set a pin tap “Lock Screen Settings” and then “Setup”. To change an existing PIN, tap “Reset your PIN”. Using the number pad, tap out a four-digit number, then tap “Enter”. Follow the instructions to confirm your new PIN by retyping the same four-digit number and tapping “Enter”. 

Information from CHESS:

-   It is not possible to recover a pin if they are using the pin lock.
    However, you can log out from that screen where you enter the pin
    and log back in to reset the pin. Also, if you log out and log back
    in, the pin should be reset.

-   People's PIN is not something we can ever see and it's not saved on
    the STAR server, just locally.

-   If a user moves the app to the background, such as if they open a
    new app, and doesn't return to the app within 10 minutes then they
    will be required to enter their pin again. If they completely close
    the app i.e. swipe the app away, they will need to enter their pin
    again.
    
**Notification Settings** - 
Users can control push notifications from STAR. Turn different notifications on or off by tapping the check box next to the notification. To receive all notifications, you should check all the boxes. To receive no notifications, you should uncheck all the boxes. Turning off your Notification settings will not affect your participation; however, you may find that having them turned on is helpful for remembering to complete the tasks. When you are done customizing your notification settings, tap the “Save” button

**Research Study Settings**
Users change their data sharing permissions by tapping the “Research Study Settings” button. 

If you tap “Change Settings” you will see a message warning you that turning off GPS and Phone/SMS data sharing will reduce your next bonus by up to $15 and asking you if would like to continue.

If you tap “Yes” you will be directed to your phone’s settings where you can change the STAR permissions. 

**Admin Setting**
Admin accounts can choose whether to make their account visible to client users by changing their Admin Settings. 

### Recovery Resources

#### Podcasts

**"A Sober Girls Guide"** - Jessica Jeboult is a Sober Girl. After trying to
get sober for nearly 10 years, Jessica is here to share her experiences
along the way to complete and utter sobriety.

**"Common Peril Podcast"** -A sarcastic take on sobriety and life as sober
young-adults in Los Angeles. We got tired of hearing recovery podcasts
that sounded like you were in another rehab group so we decided to do
something about it. "Like a speaker-tape, but more fun."

**"Elevation Recovery Podcast"- Strategies for individuals in recovery**
from opioids, alcohol, prescription drugs, meth, or any other drugs. The
Elevation Recovery Podcast's Mission is to help people transcend drug
use as well as to rapidly progress the field of recovery and treatment.

**"In Recovery With Dr. Nzinga Harrison"**- If you have a heart attack, you
go to the hospital. Kid is sick? Call the pediatrician. So why do the
rules change when it comes to recovery? When you or a loved one needs
immediate help, it's hard to know where to go or what to do. Start here.
Join Dr. Nzinga Harrison, a physician board-certified in psychiatry and
recovery medicine, Co-Founder and Chief Medical Officer of Eleanor
Health, who believes in a comprehensive, compassionate approach to
treating drug use. Whether it's heroin, pain pills, alcohol, meth, food,
sex, or anything under the sun--it's time to shift our thinking away
from 28 days and onto recovery for life. From the creators of Last Day,
this is your weekly go-to for any and all questions about addiction,
treatment, mental health, recovery, and everything in between.

**"NAPod: An (unofficial) Narcotics Anonymous Podcast"**- An (unofficial)
Narcotics Anonymous podcast featuring NA speaker meetings and workshops.
This is not a discussion podcast, simply speaker meetings and workshops
in a podcast format.

**"ODAAT Chat Recovery Podcast"** - The ODAAT (One Day At A Time) Chat
Podcast is about recovery from alcohol and drug use, and the journey of
recovery, community, and healing. Guests tell their stories of what it
was like, what happened, and where they are now. The recovery stories
they share are inspiring, funny and touching, providing hope to help
others feel like they are not alone.

"Real Recovery Talk Podcast" - Our podcast features real interviews of
individuals in recovery from substance use as well as therapists,
parents, loved ones, experts from around the industry, and others
involved in the recovery process.

**"SHAIR Podcast: Sharing Helps All in Recovery"**- Sharing Helps All in
Recovery. For lasting recovery, the most important ingredients are
community and connection. SHAIR is not only a Sobriety Podcast, it is a
global recovery Network. Join us each week as we interview individuals
from all over the world who SHAIR how they overcame adversity and
navigated through their journey of recovery. Learn how to live, how to
love, and how to heal. Welcome to the SHAIR Podcast Recovery Network

**"Talk Recovery Radio"**- Live from Vancouver's Infamous Downtown Eastside,
a block away from North America's first safe injection site. Join us
live every Thursday for Talk Recovery Radio 100.5 FM. We bring addiction
and recovery issues to the airways every Thursday on Vancouver Co-op
Radio.

**"That Sober Guy Podcast"**- That Sober Guy Podcast was created by Producer
Shane Ramer. Shane battled a 17 year alcohol and drug addiction and in
2013 he sought treatment. Less than a year later, he started That Sober
Guy Podcast as a way to share his own recovery and allow others to share
theirs

**"The Addictionary Podcast"**- Boston's own father-daughter recovered team
bring it to you straight, no chaser! Maegan and Boddy give an
uncensored, open-minded, and unconventional take on all things recovery,
and holistic health!

**"The Unrufled Podcast"**- Sondra Primeaux and Tammi Salas host this weekly
show. Their aim is to explore all of the topics that are related to
creativity in recovery. Cool, right?\
Here's their thinking: "When a habit is removed, there is a void that is
left." This show's aim is to find ways to fill that void through
creative pursuits. In each episode, they interview someone in recovery
about their journey and creative pursuits.

**"The Wagon Podcast"- As we are uniquely woven we must be uniquely**
unwoven. On the wagon, off the wagon, chasing the wagon, what wagon?
Join Minnesota's own recovery duo, Kyla Olson and Patrick Farley, as
they talk about and celebrate the many pathways of recovery

"The Way Out Podcast"- Powerful Topics and Powerful Recovery Stories in
every episode.

#### Games and Apps

**Recovery related**

*"Breathe by Dr. Jud"* -Breathe by Dr. Jud was created by psychiatrist Dr.
Jud Brewer (MD PhD) and the team at MindSciences, based on his work in
the field of habit change and the "science of self-mastery", combining
over 20 years of experience with mindfulness training and a career in
scientific research. He is passionate about understanding how our brains
work, and how to use that knowledge to help people make deep, permanent
change in their lives --- with the goal of reducing suffering in the
world at large.

*"I Am Sober"*

*"In The Rooms"*-In The Rooms is a free, digital meeting website and
social network for the recovery community. With over 600,000 members, In
The Rooms provides a virtual space for people to connect with others in
recovery around the globe. Our community offers support for those in
recovery from alcohol or drug use, as well as behavioral addictions such
as love and relationships, sex and gambling. Our newly-redesigned app
gives you recovery at your fingertips, with easy access to virtual
meetings, social networking tools, blogs, and recovery guides.

*"NA Meeting Search"* NA Meeting Search is an application developed to
help you locate Narcotics Anonymous Meetings anywhere around the world.
Also bundled with this app are the daily Just For Today meditations.
Websites and helplines for your area are also listed.

*"Sober Grid"*- The Worlds Largest Recovery App"-

This app is geared to recovery. It teaches the user how to identify
thoughts and feelings which can lead to drug use. Then it leads the user
to a daily reading geared to what they are currently experiencing which
helps change "relapse" thinking into "recovery" thinking. It was
developed by a licensed chemical dependency counselor who personally has
over 27 years of successful recovery.

*"Sober Meditations"*- Sober Meditations is a 100% free resource that
contains over 400 contemplative alcohol recovery meditations on a
variety of topics.

"All Trails: Hiking, Running, And Mountain Bike Trails"- Explore the
outdoors with AllTrails! Discover nature with hiking, biking,
backpacking and running trails around the world. Log your hike, walk,
run or mountain bike ride with our GPS activity tracker. Looking for a
good spot for camping or backpacking? The AllTrails community is a great
place to get inspired.

*"CBT Thought Diary"* - Do you feel like you're always stressed, anxious,
sad, frustrated, or unmotivated? The centerpiece of cognitive behavioral
therapy (CBT) is learning to identify negative and distorted thinking
patterns to change your emotions and your behaviors for the better. In
CBT, a "thought record" guides you through the steps of identifying,
challenging, and reinterpreting negative thinking patterns. With Thought
Diary, you can document your negative emotions, analyze flaws in your
thinking, and re-evaluate your negative thoughts into more balanced
ones. It may even help you recognize helpful ways to deal with your
negative behaviors and emotions for future situations.

*"Happify"*- Happify's science-based activities and games can help reduce
stress, overcome negative thoughts, and build greater resilience by
providing effective tools and programs to improve emotional well-being.

"Headspace Meditation and Sleep"- Headspace is your guide to mindfulness
for your everyday life. Learn meditation and mindfulness skills from
world-class experts like Headspace co-founder Andy Puddicombe, and
develop tools to help you focus, breathe, stay calm, and create balance
in your life --- whether you need stress relief or help to get restful
sleep.

*"Insight Timer"*- The number 1 free meditation app. Guided meditations,
sleep music tracks and talks led by the top meditation and mindfulness
experts, neuroscientists, psychologists and teachers from Stanford,
Harvard, the University of Oxford and more. Music tracks from
world-renowned artists. Join millions learning to meditate on Insight
Timer to help calm the mind, reduce anxiety, manage stress, and sleep
deeply.

*"Nike Training Club"*- Made for everybody and every body, Nike Training
Club offers 185+ free workouts including invigorating yoga classes, HIT,
bodyweight-only workouts you can do with minimum to no equipment, and
cardio that gets your heart rate pounding. We also have trainer-led
programs and workout collections to serve every kind of athlete in order
to get specific results, but still be flexible enough to fit into your
life.

*"Yoga; Down Dog"*

**Just for Fun**

Angry Birds

Library Audiobooks and ebooks app- Libby

Solitaire

Soduku

Tetris

#### Guided Relaxation

*"10 Minute Guided Meditation for Cravings (no music) "* -10 minute guided
mindfulness meditation to help deal with cravings and cope with
addictions, without music and voice only.

"20 Minute Guided Meditation for Cravings (no music) "-20 minute guided
mindfulness meditation to help deal with cravings and cope with
addictions, without music and voice only

"20 Minute urge surfing practice" - Use this exercise for any urge that
compels you to carry out a behavior that you want to give up, reduce, or
that has a negative impact on your life.

*"7 minute urge surfing practice"* - Welcome to this short guided
meditation for grounding and centering yourself in the midst of an urge
to engage in any behavior that you do not want to act out on. This
practice is commonly called urge-surfing.

*"8 minute urge surfing practice"*-8 minute, audio only, urge surfing
guided meditation. Urge surfing is a technique to get through a craving
or urge.

*"Guided meditation for recovery: Gulf Breeze Recovery"* - Becky Nichols,
therapist at Gulf Breeze Recovery, walks you through a guided meditation
to bring a sense of calmness to those struggling with addiction.

*"Refuge Recovery: Guided Breathing meditation"* This is a 20 minute,
guided mindfulness of breathing meditation. By watching our breath, we
can cultivate concentration and a sense of peace that will help us get
through the hard moments in life. The script for this meditation comes
from the Refuge Recovery program.

*"S.O.B.E.R. Breathing Space"*- This is an exercise you can do during a
high-risk or stressful situation, if you are upset about something, or
when you are expericing urges and cravings to use.

*"Series: Sober Meditations"*- A series of guided meditation videos
focused on supporting recovery from drug use

*"5 Minute Meditation"* -In just 5 minutes you can reset your day in a
positive way.

*"Body Scan For Sleep"*- 14 minute audio guided meditation to help you
fall asleep.

*"Body Scan for Anxiety"*- Feel more settled and calm by bringing
awareness to each part of your body, noticing your experience with a
sense of curiosity and openness. A Body Scan mindfulness meditation
created by Stop, Breathe & Think.

*"Easy 5 minute Meditation"*- Audio only - 5 minute breathing meditation

*"Meditations for difficult emotions"*- 7 minute audio meditation aimed at
coping with difficult emotions.

*"Commpassionate body scan guided meditations"* - Kayleigh Pleas, MAPP,
Wellness & Positive Psychology Coach who leads the mindfulness
meditation group at the Ruttenberg Treatment Center, narrates this 20
minute-long guided meditation video entitled "Compassionate Body Scan."

*"meditation for Positive Energy - A Deepak Chopra Guided Meditation"*-\
During this guided meditation Deepak will help you centering yourself to
find your daily dose of positive energy. So close your eyes, start
breathing. And follow Deepak voice in this Guided Meditation for
Positive Energy

*"Meditation for positive thoughts- mind body soul"* - Do you want to
fight off the negatives in your life? Are negative thoughts being a
hurdle in your journey to success? This meditation will unravel your
ability to manifest positive energy and help you reach a higher level of
consciousness.

*"Short and sweet gratitude meditation"*- 3 minute, simple and sweet
meditation.\
Really there is no going wrong with gratitude.\
Please enjoy this short break from your day as you call in all the
things, people, anything, and everything that brings your joy and that
you are grateful for.

#### Videos 

**Ted talks**

*"Addiction is a disease. We should treat it as one."*- Only one in nine
people in the United States gets the care and treatment they need for
drug abuse. A former Director of National Drug Control Policy, Michael
Botticelli is working to end this epidemic and treat people with
addictions with kindness, compassion and fairness. In a personal,
thoughtful talk, he encourages the millions of Americans in recovery
today to make their voices heard and confront the stigma associated with
drug abuse.

*"Disconnected brains: How isolation fuels opioid addiction"*- Opioids
abuse is now officially a national emergency. But why are drug use rates
spiking and what can we do about it? Neuroscientist Rachel Wurzman
shares new research about how the brain reacts to opioids, replacing the
sense of community and belonging human beings are losing. We are
beginning to understand that solving the opioid epidemic will require us
to focus on social factors surrounding those affected. Dr. Rachel
Wurzman is a Fellow with the Center for Neuroscience and Society, and a
Postdoctoral Research Fellow in Neurology with the Laboratory for
Cognition and Neural Stimulation at the University of Pennsylvania.

*"Everything you think you know about addiction is wrong."* - What really
causes addiction --- to everything from cocaine to smart-phones? And how
can we overcome it? Johann Hari has seen our current methods fail
firsthand, as he has watched loved ones struggle to manage their drug
use. As he shares in this deeply personal talk, his questions took him
around the world, and unearthed some surprising and hopeful ways of
thinking about an age-old problem.

*"From genes to addiction: How risk unfolds across the lifespan"* - What
does it mean when something like drug use or depression is genetically
influenced? Are people who are at risk destined to develop problems?
Psychologist Danielle Dick explores how our genes and our environments
come together across the lifespan to create multiple pathways that can
influence addiction.

*"How genetics and enviroment wok together to shape our destiny"* -A young
scientist in Bulgaria with lots of prestigious awards for best
scientific excellence practices I put my all energy in revealing the
secrets of the way our DNA functions.\
The way we live, the way we talk, the way we breathe and the environment
is what shapes our destinies and is controlling our genomes.....and as I
breathe in and out with science, it might be interesting to follow my
endeavours on the battlefield of Molecular Biology.

*"How isolation fuels opioid addiction"* - What do Tourette syndrome,
heroin addiction and social media obsession all have in common? They
converge in an area of the brain called the striatum, says
neuroscientist Rachel Wurzman --- and this critical discovery could
reshape our understanding of the opioid crisis. Sharing insights from
her research, Wurzman shows how social isolation contributes to opioid
use and overdose rates and reveals how meaningful human connection could
offer a potentially powerful source of recovery.

*"Listening to shame"* -Shame is an unspoken epidemic, the secret behind
many forms of broken behavior. Brené Brown, whose earlier talk on
vulnerability became a viral hit, explores what can happen when people
confront their shame head-on. Her own humor, humanity and vulnerability
shine through every word.

*"Six steps to life -altering change"* -Maurice (Moe) Egan grew up in East
Oakland surrounded by drugs and crime. Even though he found success in
sports and later working for Coretta Scott King at the Martin Luther
King Jr. Center, his drug use and criminal behavior spiraled out of
control. He found himself homeless and asleep standing up in the middle
of a busy San Francisco intersection soon to be arrested for the seventh
time. Moe and Tim Stay share six steps for transformational behavioral
change that have helped Moe and the tens of thousands of others like him
change their lives. Together, Moe and Tim share the philosophy taught at
The Other Side Academy to help others who are lost obtain lives of
sobriety, integrity, and fulfillment.

*"The harm reduction model of drug addiction treatment"* "What causes opioid addiction, and why it is so tough to combat?"-In the
1980s and 90s, pharmaceutical companies began to market opioid
painkillers aggressively, while actively downplaying their addictive
potential. The number of prescriptions skyrocketed, and so did cases of
addiction, beginning a crisis that continues today. Mike Davis explains
what we can do to reverse the skyrocketing rates of drug use and
overdose. [Directed by Good Bad Habits, narrated by Addison Anderson,
music by Landon Trimble/ Playdate].

*"Why we need to end the wat on drugs."* -Is the War on Drugs doing more
harm than good? In a bold talk, drug policy reformist Ethan Nadelmann
makes an impassioned plea to end the "backward, heartless, disastrous"
movement to stamp out the drug trade. He gives two big reasons we should
focus on intelligent regulation instead

**Recovery Related**

*"A cognitive behavioral therapy exercise for addiction recovery"* - A
Cognitive Behavioral Therapy Exercise for Addiction Recovery. Dr. KJ
Foster shares a CBT relapse prevention exercise from her Fostering
Resilience Relapse Prevention program.

*"Counselor tips: Finding support"* - Making connections with people who
will support your recovery is an important part of treatment but easier
said then done. Laura Fabick, Program Manager at ARC Community Services
in Madison, WI, talks about how to find support or make new connections.

*"Counselor tips: It's okay to struggle"* - Laura Fabick, Program Manager
at ARC Community Services in Madison, WI, discusses how struggling and
feeling challenged is a normal part of recovery.

*"Counselor tips: Preventing drug use"* - Melissa is a recovery manager at
Gosnold on Cape Cod and shares some advice and strategies to help
prevent drug use.

*"Healthy path to victory"* - A YouTube channel with helpful recovery tips,
video testimonials and helpful strategies.

*"Put the shovel down"* - A YouTube channel designed to help you understand
the science and psychology of drug use so you can conquer drug use,
recover yourself or your loved one from drug use, and get back to living
the life you want to live.

"Stop drug cravings with exercise"- We all know that exercise is good
for you, but what you probably don't know is that there is a lot of
emerging research that shows how exercise changes your neurochemistry.
The really exciting thing is you can actually use exercise to literally
change your brain chemistry to reduce drug cravings in real time.\
Join Dr. John Ratey, Harvard professor, author and expert on the effects
of exercise and the brain, as he explains the science of exercise for
treating drug use with Tree House and Dr. Dan Hendrick.

*"Struggling with addiction"* - Struggling with Addiction takes information
for qualified authors & presents it for individuals and their families
looking for information on how to live life after drug abuse.

**General Wellbeing**

*"Brene Brown on empathy"* - What is the best way to ease someone's pain
and suffering? In this beautifully animated RSA Short, Dr Brené Brown
reminds us that we can only create a genuine empathic connection if we
are brave enough to really get in touch with our own fragilities.

*"counselor Carl"* -Counselor Carl Benedict offers videos explaining issues
of life, such as codependency, grief, anger, addiction, depression,
anxiety, and stress, while teaching healthy-living skills, such as
mindfulness, conflict resolution, setting boundaries, assertiveness,
meditation, relapse prevention, healthy self-talk, principles of
recovery, and reparenting the wounded child.

*"How mindfulness empowers us: An animation narrated by Sharon
Salzburg"* -Learn about mindfulness in under 3 minutes. Mindfulness allows
us to see our thoughts and feelings as they really are, freeing us from
old ways of thinking.

*"How to defeat negative thinking: An animation"* -Negative thinking can
get the best of us at the worst of times. But there's hope! Positive
psychology Coach Derrick Carpenter reveals two key tactics that will
intercept and defeat these thoughts before they have a chance to
infiltrate your life.

*"Meditation 101: A beginner's guide"* -A two minute animated video
introduction to meditation. Are you new to meditation, and interested in
finding out how to start a practice? We'll walk you through the basics!

*"Self compassion"* -It's all too easy to be extremely tough on ourselves;
we need -- at points -- to get better at self-compassion. This animated
video provides steps to lessen negative thinking in a stressful world.

*"The problem of shame"*-Underlying so many of our emotional problems lies
one phenomenon above any other; shame. Feeling misguidedly and
disproportionately ashamed of who we are is at the root of an
extraordinary amount of disturbance, rendering us harmful to ourselves
and to the world.

*"Where does compassion really come from"* -Can compassion be learned? The
answer is yes! Sometimes, all it takes is truly paying attention to the
people around us.

*"Why mindfulness is a superpower: An animation"* -Practicing mindfulness
is one of the single most powerful things you can do for your wellbeing.
This short animated video explains the power and benefits of
mindfulness.

*"Yoga with Adriene"* -WELCOME to Yoga With Adriene! Our mission is to
connect as many people as possible through high-quality free yoga
videos.\
We welcome all levels, all bodies, all genders, all souls!

#### Articles
**Learn about recovery**

*"Can addiction be treated sucessfully"* - Yes. Addiction is a treatable,
chronic disorder that can be managed successfully.\
Research shows that combining behavioral therapy with medications, if
available, is the best way to ensure success for most patients.\
The combination of medications and behavioral interventions to treat a
substance use disorder is known as medication-assisted treatment.
Treatment approaches must be tailored to address each patient's drug use
patterns and drug-related medical, psychiatric, environmental, and
social problems.

*"Does drug and alcohol abuse cause mental disorders, or vice versa"* -
Drug and alcohol abuse and mental disorders often occur at the same
time. This is referred to as co-existing conditions or comorbidities.
Over half of the people with a drug and alcohol abuse also have another
mental health issue. This doesn't necessarily mean that one caused the
other.\
There are three ways to look at this; In some cases mental illness can
lead to addiction. In other cases, drug and alcohol abuse can cause a
mental illness or lastly both drug abuse and a mental disorder are both
caused by a common risk factor.

*"Does it really matter how we talk about addiction?"* -The old adage,
"Sticks and stones may break my bones, but words can never hurt me,"
implies words cannot convey harm. Today, however, more and more research
on stigma is showing that words truly can hurt people, and in ways that
the users of those words may not anticipate. This seems to be especially
true when those words serve to reinforce misconceptions and
misrepresentations of already heavily stigmatized medical conditions.

*"From pills to fentanyl: Three personal stories that show how the opioid
crisis evolved"*- Three drugs are responsible for creating the deadly
U.S. opioid epidemic: prescription pain pills, heroin and fentanyl. As
of 2018, the crisis had claimed more than 400,000 lives.\
Yet the faces of some victims remain hidden. Grieving families
embarrassed by the stigma of drug abuse write "passed peacefully at
home" in obituaries.The Washington Post spoke with families and friends
of more than 70 victims that span the epidemic. Here are some of their
stories, remembered through the lens of their families.

*"Recovery research institute: Resources"* - The Recovery Research
Institute is a leading nonprofit research institute of Massachusetts
General Hospital, an affiliate of Harvard Medical School, dedicated to
the advancement of drug use treatment and recovery.

"Soberocity: Connecting with people and sharing stories of recovery"-We
are a one-of-a-kind community, created especially for those who are
living a sober life and are looking for sober events to attend and for a
like-minded community.\
Soberocity is for people from all walks of life who can now connect, and
share their individual journeys of recovery while encouraging sobriety
and sober-living in others. In other words, Soberocity is a place where
individuals who are invigorated about all the opportunities that come
from living a healthy lifestyle.

*"Stages of addiction and recovery"* - While more research is needed,
recovery models remain an effective means for understanding change
behavior and the process of moving from active drug use into long-term
recovery.\
This article from recoveryanswers.org discusses 3 models:

-   Transtheoretical Stages of Change Model

-   The Life Course Perspective

-   The Hierarchy of Needs Perspective

"Straight up information about addiction and recovery"- The Fix is a
great resource for facts and support. On the blog, readers can browse
first-person recovery journeys, new and alternative treatment
information, current research and studies, and much more.

"The brain in recovery"- There are 3 key things to know about the brain
in recovery.\

1.  Some characteristics of drug use are similar to other chronic
    diseases

2.  Substances of misuse trick the brains reward system

3.  The Brain Can Recover- but it takes time!

*"Unraveling: How women are surviving the opioid crisis."* - Each day, more
than 130 lives will be lost to an opioid overdose. A year after the
crisis was declared a public health emergency, it was reported that
Americans are more likely to die from an opioid overdose than from a car
crash. Women, who are most often the center of our care networks, have
been affected in profound and myriad ways. They've buried children or
taken in those of family members unfit to care for them. They've been
overprescribed for pain management and underserved when the addiction
set in. Over the course of the next eight weeks, we'll be sharing their
stories.

*"What is the impact of addiction"* - Issues related to drug use are among
the top public health problems in the U.S. and other nations around the
world.

1.  Drug use can have an impact on health for the user, their social
    network, their community, society, and the economy.

2.  According to studies involving clinical experts and scientists (Nutt
    et al., 2010), alcohol is considered to be the most harmful drug due
    its indirect effects involving other people, followed by heroin and
    cocaine. Alcohol is also considered to be the third most harmful in
    terms of effects directly impacting the user, after heroin and
    cocaine.

3.  The impact of drug use may be reduced with early intervention
    (Dennis et al., 2004). Alcohol and other drug use is the principle
    contributor to disability-adjusted life years lost for young people
    (Mokdad et al., 2016).

4.  Early intervention may help minimize substance use disorder in
    adulthood, as 90% of adults with substance use disorder first used
    before the age of 18, and 50% started before the age of 15.

**Workbooks**

*"Challenging Automatic Thoughts"*

*"Decisional Balance Exercise"* - When people make decisions, they look at
the costs and benefits of choices they could make. Decisional balance is
a useful tool to help you make tough decisions during your recovery.

*"Journaling in recovery: A list of recovery journal prompts & tips to
get started"* - Journaling in recovery can be a helpful tool to guide
your healing process. You may use a journal to record your struggles
through the recovery process or to identify accomplishments in healing.
Journals are even useful to help you work through painful or difficult
emotions that may be hard to annunciate to a counselor or therapist, but
easier to jot down on paper/or digital device. No matter what you decide
to put in your journal, the writing process can be therapeutic in a
variety of different ways

*"MAP: My Action Plan for Relapse Prevention"* - Through assessing the
relapse prevention needs of patients, reviewing the literature on
relapse, and evaluating available relapse prevention resources,
Montgomery County Emergency Services developed this workbook as a tool
to empower individuals to begin to build a MAP to support emotional,
mental and spiritual well being.

*"Missions Consumer Recovery Workbook"* - This free recovery workbook
contains exercises multiple exercises to help those in recovery: for
example, to name and conquer adversaries within and without, to face
your fears, to think through your options in difficult situations, and
to realize what can cause relapse and what can help you avoid "slips."
There are no right answers. Your answers are your answers and no one
else's. Hearing others who are also courageously exploring what is true
for them is important, though: hearing them can often help you hear
yourself.

*"Risk-Reward Analysis For Drug Use"*- This exercise is an important tool
for establishing motivation if you are contemplating quitting drug use.
It will also have value as you work toward quitting your drug use or
other maladaptive behavior. During challenging situations, your
Risk-Reward Analysis can be an anchor for you to refresh your memory of
your reasons for quitting.

"Seemingly Irrelevant Decision (SID)"

**General Wellbeing**

*"Attentive Listening"*

*"Body Language (Non-verbal Communication)*

*"Criticisms"*

*"Expressing Yourself Assertively"*

*"Giving and Receiving Compliments"*

*"Try the 5-3-1 -practice- Center for Healthy Minds."*

*"9 facts about addiction people usually get wrong"*

*"Life after relapse- How to bounce back and start over"*

*"Preventing opioid overdose"*

*"Repairing relationship after rehab"*

*"What are the most common drug use triggers"*

**Quick Recovery Tips**

*"9 Facts about addiction people usually get wrong"*-This article comes
from the Partnership for Drug-Free Kids so it's aimed at parents, but
there's a lot of great information that's relevant to anyone struggling
with drug use.

*"Life after relapse- How to bounce back and start over"*-According to the
National Institute on Drug Abuse, 40 to 60 percent of people who go
through addiction treatment programs go on to relapse at least once. In
fact, many people relapse multiple times before finally achieving a full
recovery.\
\
You can take some comfort in knowing relapse is common. But how do you
handle it? Click on this link for some tips from smartrecovery.org

*"Preventing an opioid overdose"*-Know the signs. Save a life. This fact
sheet gives you the factors that could cause an opioid overdose, the
common signs and symptoms of an opioid overdose, and tips on what to do
if you think someone is overdosing

*"Repairing relationships after rehab"*- Rebuilding connections and
mending broken ties is not easy. Here are 5 tips to help you get
started.

*"What are the most common drug use triggers?"*-The 10 most common drug
use triggers include:\

1.  Being around drugs or alcohol, drug or alcohol users, or places
    where you used or bought drugs or alcohol

2.  Feelings we perceive as negative: anger, sadness, loneliness, guilt,
    fear, and anxiety

3.  Positive feelings that make you want to celebrate

4.  Boredom

5.  Getting high on any drug

6.  Physical pain

7.  Listening to alcohol and drug stories and just dwelling on getting
    high

8.  Suddenly having a lot of cash

9.  Using prescription drugs that can get you high even if you use them
    properly

10. Believing that you no longer have to worry and that it is safe for
    you to use occasionally. That is, that you are no longer addicted
    and will not crave drugs or alcohol when you are in any of the above
    situations, or by anything else.

**Book Recommendations**


*"A Million Little Pieces"* By James Frey-A story of drug and alcohol use
and rehabilitation as it has never been told before. Recounted in
visceral, kinetic prose, and crafted with a forthrightness that rejects
piety, cynicism, and self-pity, it brings us face-to-face with a
provocative new understanding of the nature and the meaning of
recovery.\
By the time he entered a drug and alcohol treatment facility, James Frey
had taken his addictions to near-deadly extremes. He had so thoroughly
ravaged his body that the facility's doctors were shocked he was still
alive. The ensuing torments of withdrawal, and the never-ending urge to
use chemicals, are captured with a vitality and directness that recalls
the seminal eye-opening power of William Burroughs's Junky.\
But A Million Little Pieces refuses to fit any mold of drug literature.
Inside the clinic, James is surrounded by patients as troubled as he is
-- including a judge, a mobster, a one-time world-champion boxer, and a
fragile former prostitute to whom he is not allowed to speak ó but their
friendship and advice strikes James as stronger and truer than the
clinic's droning dogma of How to Recover. James refuses to consider
himself a victim of anything but his own bad decisions, and insists on
accepting sole accountability for the person he has been and the person
he may become--which runs directly counter to his counselors' recipes
for recovery.\
James has to fight to find his own way to confront the consequences of
the life he has lived so far, and to determine what future, if any, he
holds. It is this fight, told with the charismatic energy and power of
One Flew over the Cuckoo's Nest, that is at the heart of A Million
Little Pieces: the fight between one young man's will and the
ever-tempting chemical trip to oblivion, the fight to survive on his own
terms, for reasons close to his own heart.\
A Million Little Pieces is an uncommonly genuine account of a life
destroyed and a life reconstructed. It is also the introduction of a
bold and talented literary voice.

*"Blackout: Remembering the Things I Drank to Forget"*- For Sarah Hepola,
alcohol was "the gasoline of all adventure." She spent her evenings at
cocktail parties and dark bars where she proudly stayed till last call.
Drinking felt like freedom, part of her birthright as a strong,
enlightened twenty-first-century woman.\
But there was a price. She often blacked out, waking up with a blank
space where four hours should be. Mornings became detective work on her
own life. What did I say last night? How did I meet that guy? She
apologized for things she couldn't remember doing, as though she were
cleaning up after an evil twin. Publicly, she covered her shame with
self-deprecating jokes, and her career flourished, but as the blackouts
accumulated, she could no longer avoid a sinking truth. The fuel she
thought she needed was draining her spirit instead.\
A memoir of unblinking honesty and poignant, laugh-out-loud humor,
Blackout is the story of a woman stumbling into a new kind of adventure
-- the sober life she never wanted. Shining a light into her blackouts,
she discovers the person she buried, as well as the confidence,
intimacy, and creativity she once believed came only from a bottle. Her
tale will resonate with anyone who has been forced to reinvent or
struggled in the face of necessary change. It's about giving up the
thing you cherish most -- but getting yourself back in return.

*"Delicious Foods- By James Hannaham"* -Held captive by her employers --
and by her own demons -- on a mysterious farm, a widow struggles to
reunite with her young son in this uniquely American story of freedom,
perseverance, and survival.\
Darlene, once an exemplary wife and a loving mother to her young son,
Eddie, finds herself devastated by the unforeseen death of her husband.
Unable to cope with her grief, she turns to drugs, and quickly forms an
addiction. One day she disappears without a trace.\
Unbeknownst to eleven-year-old Eddie, now left behind in a
panic-stricken search for her, Darlene has been lured away with false
promises of a good job and a rosy life. A shady company named Delicious
Foods shuttles her to a remote farm, where she is held captive,
performing hard labor in the fields to pay off the supposed debt for her
food, lodging, and the constant stream of drugs the farm provides to her
and the other unfortunates imprisoned there.\
In Delicious Foods, James Hannaham tells the gripping story of three
unforgettable characters: a mother, her son, and the drug that threatens
to destroy them. Through Darlene's haunted struggle to reunite with
Eddie, through the efforts of both to triumph over those who would
enslave them, and through the irreverent and mischievous voice of the
drug that narrates Darlene's travails, Hannaham's daring and
shape-shifting prose infuses this harrowing experience with grace and
humor.\
The desperate circumstances that test the unshakeable bond between this
mother and son unfold into myth, and Hannaham's treatment of their
ordeal spills over with compassion. Along the way we experience a tale
at once contemporary and historical that wrestles with timeless
questions of love and freedom, forgiveness and redemption, tenacity and
the will to survive.

*"Drinking a Love Story- by Caroline Knapp"* -Fifteen million Americans a
year are plagued with alcoholism. Five million of them are women. Many
of them, like Caroline Knapp, started in their early teens and began to
use alcohol as "liquid armor," a way to protect themselves against the
difficult realities of life. In this extraordinarily candid and
revealing memoir, Knapp offers important insights not only about
alcoholism, but about life itself and how we learn to cope with it.\
It was love at first sight. The beads of moisture on a chilled bottle.
The way the glasses clinked and the conversation flowed. Then it became
obsession. The way she hid her bottles behind her lover's refrigerator.
The way she slipped from the dinner table to the bathroom, from work to
the bar. And then, like so many love stories, it fell apart. Drinking is
Caroline Kapp's harrowing chronicle of her twenty-year love affair with
alcohol.\
Caroline had her first drink at fourteen. She drank through her years at
an Ivy League college, and through an award-winning career as an editor
and columnist. Publicly she was a dutiful daughter, a sophisticated
professional. Privately she was drinking herself into oblivion. This
startlingly honest memoir lays bare the secrecy, family myths, and
destructive relationships that go hand in hand with drinking. And it is,
above all, a love story for our times---full of passion and heartbreak,
betrayal and desire---a triumph over the pain and deception that mark an
alcoholic life.

*"Graceland- by Chris Abani"* -The sprawling, swampy, cacophonous city of
Lagos, Nigeria, provides the backdrop to the story of Elvis, a teenage
Elvis impersonator hoping to make his way out of the ghetto. Broke,
beset by floods, and beatings by his alcoholic father, and with no job
opportunities in sight, Elvis is tempted by a life of crime. Thus begins
his odyssey into the dangerous underworld of Lagos, guided by his friend
Redemption and accompanied by a restless hybrid of voices including The
King of Beggars, Sunday, Innocent and Comfort. Ultimately, young Elvis,
drenched in reggae and jazz, and besotted with American film heroes and
images, must find his way to a GraceLand of his own.\
Nuanced, lyrical, and pitch perfect, Abani has created a remarkable
story of a son and his father, and an examination of postcolonial
Nigeria where the trappings of American culture reign supreme.

*"Gun, Needle, Spoon- By Patrick O'Neil"* - This memoir follows a punk rock
pioneer on his slide into drug abuse and life as an armed robber, all
the way through life in recovery and what it's like to look back on
those times, knowing all the while that he is still under the threat of
three strikes, a twenty-five-to-life prison sentence waiting. He has no
choice but to deal with it all drug free.

*"Guts- By Kristen Johnston"*- A harrowing and hysterical memoir by the
two-time Emmy Award-winning actress from the hit television show 3rd
Rock from the Sun.\
"It felt like I was speeding on the Autobahn toward hell, trapped inside
a DeLorean with no brakes. And even if I could somehow stop, I'd still
be screwed, because there's no way I'd ever be able to figure out how to
open those insane, cocaine-designed doors."

*"High on Arrival- By Makenzie Phillips"*- Not long before her fiftieth
birthday, Mackenzie Phillips walked into Los Angeles International
Airport. She was on her way to a reunion for One Day at a Time, the
hugely popular 70s sitcom on which she once starred as the lovable rebel
Julie Cooper. Within minutes of entering the security checkpoint,
Mackenzie was in handcuffs, arrested for possession of cocaine and
heroin.\
Born into rock and roll royalty, flying in Lear jets to the Virgin
Islands at five, making pot brownies with her father's friends at
eleven, Mackenzie grew up in an all-access kingdom of hippie freedom and
heroin cool. It was a kingdom over which her father, the legendary John
Phillips of The Mamas & the Papas, presided, often in absentia, as a
spellbinding, visionary phantom.\
When Mackenzie was a teenager, Hollywood and the world took notice of
the charming, talented, precocious child actor after her star-making
turn in American Graffiti. As a young woman she joined the nonstop party
in the hedonistic pleasure dome her father created for himself and his
fellow revelers, and a rapt TV audience watched as Julie Cooper wasted
away before their eyes. By the time Mackenzie discovered how deep and
dark her father's trip was going, it was too late. And as an adult, she
has paid dearly for a lifetime of excess, working tirelessly to
reconcile a wonderful, terrible past in which she succumbed to the power
of drug use and the pull of her magnetic father.\
As her astounding, outrageous, and often tender life story unfolds, the
actor-musician-mother shares her lifelong battle with personal demons.
She overcomes seemingly impossible obstacles again and again and
journeys toward redemption and peace. By exposing the shadows and
secrets of the past to the light of day, the star who turned up High on
Arrival has finally come back down to earth -- to stay.\

*"How to grow up- By Michelle Tea"*-As an aspiring young writer in San
Francisco, Michelle Tea lived in a scuzzy communal house: she drank; she
smoked; she snorted anything she got her hands on; she toiled for the
minimum wage; she dated men and women, and sometimes both at once. But
between hangovers and dead-end jobs, she scrawled in notebooks and
organized dive bar poetry readings, working to make her literary dreams
a reality.\
In How to Grow Up, Tea shares her awkward stumble towards the life of a
Bona Fide Grown-Up: healthy, responsible, self-aware, and stable. She
writes about passion, about her fraught relationship with money, about
adoring Barney's while shopping at thrift stores, about breakups and the
fertile ground between relationships, about roommates and rent, and
about being superstitious ("why not, it imbues this harsh world of ours
with a bit of magic"). At once heartwarming and darkly comic, How to
Grow Up proves that the road less traveled may be a difficult one, but
if you embrace life's uncertainty and dust yourself off after every
screw up, slowly but surely, you just might make it to adulthood.

*"In Pain: A Bioethicist's Personal Strugfle with Opioids- By Travis N
Rieder"* - A bioethicist's harrowing memoir of opioid dependence and
withdrawal--and a clarion call to challenge the status quo of healthcare
and of medicine itself--[this book] reveals the lack of crucial
resources and structures to responsibly manage pain in America. Travis
Rieder's terrifying journey down the rabbit hole of opioid dependence
began with a motorcycle accident in 2015. One month and several
surgeries later, Travis was on painkillers around the clock. The drugs
he received were both miraculous and essential to his recovery--for a
time. But the most profound suffering Travis would endure arrived months
after the accident, when he went into acute opioid withdrawal while
following his physician's orders. Over the course of four excruciating
weeks, Rieder experienced firsthand, all day long and through the night,
what it means to be 'dope sick'--the absolute physical and mental agony
that is opioid withdrawal. Clueless how to taper off these intensely
powerful painkillers, Travis turned to his doctors, who suggested that
he go back on the drugs and simply try again later. Rieder's experience
exposes a dark secret of American healthcare: the crisis currently
facing us is actually an unsurprising and inevitable consequence of a
culture deeply conflicted about opioids and a system grossly inept at
managing them. As he recounts his own brutal story of pain and pills,
Rieder provides the fascinating history and trajectory of these drugs,
from their invention in the 1800s through a long period of opiophobia to
the eventual warm embrace of these medications that led to an
environment of aggressive, even reckless, prescribing. Here rigorous
examinations of the science of pain and addiction are considered
alongside analyses of the systemic and cultural barriers we must
overcome if we are to address the problem effectively on both a local
and a global scale.\
\
[This book] is not only a gripping personal account of drug dependence,
but also a groundbreaking exploration of the complex causes of our
opioid epidemic and a path to resolving the crisis through provider
education, policy, and alternative treatment advocacy. Rieder makes very
clear that the opioid crisis exists against a backdrop of real,
debilitating pain that providers cannot ignore but can learn to treat
more effectively and safely. Pain management is profoundly broken in
America, and the result is devastating for both patients and those at
risk for addiction. But we do not, Rieder argues, have to accept this
situation. By changing medical practice, adopting reasonable drug
policies, and altering the way we view those who take drugs (both
prescription and not), we can reduce suffering and save lives; we can
give people the care they deserve.

"Permanent Midnight- By Jerry Stahl"- Jerry Stahl's seminal memoir of
drug addiction and a career in Hollywood, Permanent Midnight is a
classic along the lines of Hubert Selby, Jr.'s Last Exit to Brooklyn.
Illuminating the self-loathing and self-destruction of an addict's inner
life, Permanent Midnight follows Stahl through the dregs of addiction
and into recovery. In 1998, Ben Stiller, Owen Wilson, and Maria Bello
starred in a film version of Permanent Midnight to much acclaim. Nic
Sheff, author of Tweak, writes the introduction to this edition.

*"Terry: My Daughter's Life- and- Death Struggle with Alcoholism- By
George McGovern"* -Just before Christmas 1994 Terry McGovern was found
frozen to death in a snowbank in Madison, Wisconsin, where she had
stumbled out of a bar and fallen asleep in the cold. Just forty-five
years old, she had been an alcoholic most of her life. Now, in this
harrowing and intimate reminiscence, her father, former Senator George
McGovern, examines her diaries, interviews her friends and doctors,
sifts through medical records, and searches for the lovely but fragile
young woman who had waged a desperate, lifelong battle with her
illness.\
\
What emerges is the portrait of a woman who was loved by everyone but
herself. Surrounded by devoted parents, caring siblings, and two young
daughters of her own, Terry maintained an appearance of control but was
haunted by the twin demons of alcohol and depression. Her story is a
heartbreaking tale of her attempts at sobriety, the McGovern family's
efforts to help her---and the failure of both. With courage and
compassion, George McGovern addresses a private tragedy with an honesty
rarely achieved by a public figure, looking candidly at his inability to
save his child. A primer for other families who live with addiction,
McGovern's book is filled with wisdom and an understanding that can come
only from sharing his tremendous loss with others.

*"Unwifeable: A memoir- By Mandy Stadmiller"* - Provocative, fearless, and
dizzyingly uncensored, Mandy spills every secret she knows about dating,
networking, comedy, celebrity, media, psychology, relationships,
addiction, and the quest to find one's true nature. She takes readers
behind the scenes (and name names) as she relays her utterly addictive
journey.\
\
Starting in 2005, Mandy picks up everything to move across the country
to Manhattan, looking for a fresh start. She is newly divorced,
thirty-years-old, with a dream job at the New York Post. She is ready to
conquer the city, the industry, the world. But underneath the glitz and
glamour, there is a darker side threatening to surface. The drug-fueled,
never-ending party starts off as thrilling...but grows ever-terrifying.
Too many blackout nights and scary decisions begin to add up. As she
searches for the truth behind the façade, Mandy realizes that falling in
love won't fix her---until she learns to accept herself first.

#### Resources Near You 

**Treatment Resources**

*"Addiction Center: Locate a treatment center near you"* - Recovery on your
own is not only dangerous during the initial detox, it is also more
likely to result in drug use later on. Addiction treatment centers
provide a monitored environment where you will get the medical attention
you need, as well as the emotional support to overcome drug or alcohol
use. Addiction Center provides information about different types of
treatment programs, provides a treatment locator to find centers in your
area, and has treatment providers on call (833-523-1311) or available
over instant messaging on their website to help you locate treatment
resources near you.

*"FindTreatment.gov"* -FindTreatment.gov helps you find substance use
treatment resources near you and provides useful information about what
to expect during treatment, paying for treatment, different types of
treatment, and other commonly asked questions about the treatment
process. Enter your zip code online or call 1-800-662-HELP (4357) to
talk to someone to help locate services in your area.

*"Google Recover Together: Find Local Support"*-Google Recover offers a
simple way to find local drug use treatment and support in your state.
Select your state from the drop-down box to under "Find local support"
to learn how to connect to information and resources if you or someone
you know is seeking help.\
"SAMHSA Behavioral health treatment"- Check out the SAMHSA Behavioral
Health Treatment Services Locator, a confidential and anonymous source
of information for persons seeking treatment facilities in the United
States or U.S. Territories for substance use/addiction and/or mental
health problems.

*"SAMHSA- Opioid treatment program directory"* -Use this search tool to
view the opioid treatment programs in your state.

"Start your recovery: Find local treatment options"- Find local
substance use recovery centers, counseling, and support groups.

**Recovery Support**

"Google's recovery resource tool"-Even when apart, our voices are
united. The #RecoveryMovement celebrates the 23 million Americans
recovering from drug use, and paves the way for the 20 million still
struggling to seek treatment. Our voices matter.

"In the rooms- A global recovery community"-Ken Pomerance and Ron
Tannebaum started In The Rooms (ITR) with a simple goal in mind: to give
those in recovery a place to meet and socialize when they're not in
face-to-face meetings. This basic concept has grown into a global online
community with over 650,000 members who share their strength and
experience with one another daily. Through live meetings, discussion
groups, and all the other tools In the Rooms has to offer, people from
around the world connect with one another and help each other along
their recovery journeys.

"LifeRing secular recovery"- LifeRing Secular Recovery is an
abstinence-based, anonymous organization dedicated to providing a safe
meeting space where you can experience a non-judgmental recovery
conversation with your peers. They do this through the lens of
LifeRing's "3-S" philosophy of Sobriety, Secularity, and Self-Help.
Click below to read more.

"Narcotics Anonymous- Meeting locator"-Use this search tool to locate
meetings near you or to locate helplines and websites for local groups
near you.

"National harm reduction coalition- Find harm reduction resources near
you"- Harm reduction aims to connect people who use drugs to resources
and community to thrive. Whether you use drugs, or love someone who
does, this page is an access point to resources that support safer drug
use.

"Never use alone" -If you are going to use by yourself, call us! You
will be asked for your first name, location, and the number you are
calling from. An operator will stay on the line with you while you use.
If you stop responding after using, the operator will notify emergency
services of an \\"unresponsive person\\" at your location.

"SHE RECOVERS foundation" - A non-profit charity that seeks to connect
women in recovery through virtual platforms and encourages women to
"develop their own holistic recovery patchwork"

"Smart recovery resource page"- Self-Management And Recovery Training
(SMART) is a global community of mutual-support groups. At meetings,
participants help one another resolve problems with drugs and alcohol,
or to activities such as gambling or over-eating). Participants find and
develop the power within themselves to change and lead fulfilling and
balanced lives guided by our science-based and sensible 4-Point Program\

"Virtual recovery resources"-Tip sheet created by SAMHSA in response to
the COVID epidemic and the need for virtual recovery support.

**General Support**

*"Crisis text line"* -Text HOME to 741741 from anywhere in the United
States, anytime. Crisis Text Line is here for any crisis. A live,
trained Crisis Counselor receives the text and responds, all from our
secure online platform. The volunteer Crisis Counselor will help you
move from a hot moment to a cool moment.

*"For issues with housing, food, other survival needs"*- The 211 network
in the United States responds to more than 14 million requests for help
every year. Most calls, web chats, and text messages are from people
looking for help meeting basic needs like housing, food, transportation,
and health care.\
211 connects you to expert, caring help. Every call is completely
confidential

*"Lifeline: National suicide prevention line"* -Phone: 1-800-273-8255\
The Lifeline provides 24/7, free and confidential support for people in
distress, prevention and crisis resources for you or your loved ones,
and best practices for professionals.

*"Manage your wellness during the COVID-19 outbreak"*

*"Mental health resources for Black, Indigenous, People of color"* - Your
local Mental Health America affiliate is an excellent resource for
information about local programs and services including affordable
mental health treatment services. Enter your city, state, or zip code to
find options to get connected to mental health resources in your area.

*"National domestic violence hotline"* - Advocates at the National
Domestic Violence Hotline are here to listen without judgement and help
you begin to address what's going on in your relationship. Their
services are always free and available 24/7.

"Psychology today therapy directory"- You can use Psychology Today's
Therapy Directory to search for mental health professionals in your
area. You can search by zip code, city, last name, etc. For each
provider listed, you can read about their therapy approach, specialty
areas, information about their fees including whether they accept
insurance and whether they offer sliding scale fees, as well as their
credentials and contact information. There are a variety of options for
sorting your results to find providers who most closely match your
needs. You can also send them an initial e-mail.

*"Warmlines- Need to talk to someone?"* - Warmlines were created to give
people support when they just need to talk to someone. Speaking to
someone on these calls are typically free, confidential, and run by
people who understand what it's like to struggle with mental health
problems.

**Drug/medication disposal**

*"Google Maps: Drug Disposal locations near you"*- Uses your location to
show you nearby places to drop off unused drugs.

*"How to safely dispose of unused or expired medicine"*- Learn how to
properly get rid of old, expired, unwanted, or unused medicines. This
video describes health risks---including potential overdose---for your
family of keeping unused medicines in your home. It explains your drug
disposal options, which include drug take-back locations, flushing, and
household trash.

*"safe needle disposal"*- Each year approximately 9 million sharps users
will administer at least 3 billion injections outside health care
facilities. SafeNeedleDisposal.org provides a one-stop shop for people
to learn how to safely dispose of used sharps wherever they are.

#### My Motivation
#### My Gratitude

### Coping with Cravings

Cravings are a normal part of the recovery process. While cravings can feel extremely powerful in the moment, it is important to remember that cravings do not last forever. In fact, most cravings usually only last a few minutes. Here are some things that help people cope with cravings:

1. Distraction. Distracting activities can help keep your mind off of your cravings until they pass. Here are some ideas:
 * Exercise or go for a walk
 * Play a game on your phone
 * Listen to a recovery podcast
 * Read a book or article
 * List to your favorite music
 * Watch a TED talk or other video
2. Talking with others. Talking with friends and family, or listening to others discuss their own recovery experiences, can help you feel supported while waiting for cravings to pass. Here are some ideas:
 * Post a message to the discussion group
 * Listen to a podcast sharing recovery stories
 * Find a recovery meeting or support group
 * Text or call a support line
3. Mental Techniques. There are a number of mindfulness and positive thinking skills that help individuals learn to let go of cravings, accept them for what they are, and cope with cravings until they pass. Here are some ideas:
 * Try urge surfing
 * Review your motivations for recovery
 * Do a short mindfulness meditation
 * Review your gratitude list
 * Watch a motivational video
 * Journal about your recovery progress


### Study Information
#### STAR Guidelines
*The purpose of the STAR Guidelines is to set expectations for  Participant interactions with the discussion board and in communication with STAR Staff.*

> By joining STAR, you agree to abide by all rules and guidelines when
communicating on STAR message boards, direct messages, and during phone
calls with STAR staff. Our Guidelines are designed to ensure all
participants and staff are protected and are treated professionally and
with respect. All in-app messages, posts, and phone calls with staff are
regularly reviewed by the STAR team, and staff will remove any
discussion post, comment, or individual member who does not adhere to
stated rules and guidelines.

> **Guideline 1: Always Use Respectful Language** - 
It is important to us that the STAR app and procedures create a space
where individuals feel comfortable, safe, and empowered to communicate
while supporting their recovery. Therefore, STAR will not tolerate
harassment, hate speech, violent or vulgar remarks, or exclusionary
language of any kind on app discussion boards, direct messages, or via
phone/email/direct message communications with STAR staff. This includes
hurtful or targeted language against someone on the basis of their race,
ethnicity, national origin, disability, financial class, religious
affiliation, sex, gender identity, sexual orientation, or any other
individual characteristics. Whenever you are posting on message boards,
sending direct messages, or talking on the phone with STAR Staff,
remember that there's a human being on the other end.

> **What we expect from you:** For the safety and comfort of all study
staff and participants in the STAR study, we expect you to use
respectful language in all communication. This includes not making any
inappropriate, flirtatious, threatening, or rude comments to study staff
or other study participants.\
In Direct Messages with study staff and in posts to the Discussion
Board, do not use offensive, obscene, or sexually explicit language,
jokes, or stories. Do not use derogatory names or labels (directly or
implied) when referring to individuals or groups. Any use of this
language will result in an immediate warning and possible subsequent
removal from the STAR Study

> **What you can expect from us:** Every member of the STAR team is
committed to maintaining a high standard for communication with
participants. We will always use polite and respectful language as
outlined above when communicating with you. If you are ever concerned
that a member of the STAR team is not meeting this standard, please to
not hesitate to share that concern. Our team will review all language
from staff and participants and remove content that does not meet this
standard.

> **Guideline 2: Use a Professional Communication Style**

> All posts should be professional and courteous. Accepted internet
standards for professional online communication include not using
all-caps (or SHOUTING) in your posts, maintaining a civil tone,
respecting the privacy of others, and staying on-topic.

> **What we expect from you:** Please communicate with staff and other
STAR participants as you would in a professional work setting. You may
send direct messages to staff with questions, comments, or concerns
about the STAR study at any time. However, all Direct Messages to staff
should be on topic and professional in tone. Similarly, posts and
replies to topics on discussion boards should remain on topic and
maintain a professional tone. To stay on topic, please do not overshare
personal information or ask personal questions to STAR staff or other
participants and limit your communication to STAR procedures or posted
discussion topics. To maintain professional tone, we ask that you do not
post or comment on discussion boards, direct message staff, or
call/email STAR staff when you are feeling highly emotional or are under
the influence of drugs or alcohol. Please wait to send all communication
until you feel you are in a calm and comfortable state of mind.

> **What you can expect from us:** Our team is committed to responding to
all messages from our participants in a prompt and professional manner.
In addition to the standards outlined above, you can expect that any
direct message or phone call received by STAR staff to be responded to
within 1 - 2 business days of the message being received. If you are
ever reaching out to report an issue with the STAR app, you will not be
penalized for study tasks missed while waiting for a response from study
staff.

> **Guideline 3: Safe Communication/Privacy**

> Communications on the STAR app and with STAR staff are secure to protect
your privacy. Since posts and comments on message boards are able to be
viewed by other authorized STAR users, we request that all users follow
general internet safety guidelines to prevent unintentional sharing of
personal information to others. When writing on STAR discussion boards,
avoid sharing personal or private information that you would not be
willing to share with a total stranger. For example, you should never
share your full name, your phone number, your address, or your social
security number. If you would shred it, don't share it. STAR staff will
remove any posts where someone is attempting to gather personal or
private information from other users on the platform.

> **What we expect from you:** Due to the personal nature of the STAR
study, we ask that you avoid sharing personal identifying information
about yourself or any other participants. In the course of your
participation, you may discover that you know other people also
participating in the study. While you are free to discuss details of
your participation in the study with people on other platforms, please
be mindful of the information you are sharing within the STAR app to
make sure that you are not accidentally sharing personal information
about someone else. The STAR team reserves the right to remove anything
that that they deem to contain or attempt to gather personal identifying
information. Any questions about what may be too sensitive to post to
discussion boards should be directed to the STAR Help account via DM.

> **What you expect from us:** You should expect that we will always
consider your safety to be our top priority. This includes having
multiple protocols in place to protect your privacy, including storing
your contact information in a locked location that is separate from your
data, restricting access to your contact information, and labeling all
of your data with an anonymous id number, (a full list of the privacy
protections can be found in the Consent Form). Additionally, we will
never post or share any information about you with any other STAR
participants. Even if you know other participants in the STAR study, we
will never share any information about participants with any other
participants.

> **Review Process -**
 We maintain a record of all messages and posts sent within the STAR app,
as well as all phone and email conversations with STAR staff outside of
the app. These records are regularly reviewed by our STAR team to ensure
communication follows our stated guidelines. If a member of the STAR
team detects language or behavior that does not follow our guidelines, a
private written warning will be sent to individuals following their
first offense. A second offense may result in the person's account being
removed from the app and withdrawal from the STAR study.
Study staff will always be available to discuss decisions about warnings
or withdrawal. These guidelines are meant to serve as general rules for
the type of behavior that will result in a warning or possible
withdrawal from the STAR study. This is not an exclusive list. The STAR
team reserves the right to determine if a participant has behaved
inappropriately.

#### How To
#### Privacy Policy/Informed Consent 