# STAR App Guidelines training video script

(The purpose of this video tutorial is to explain the STAR app
guidelines)

**Script**

*In this video, we are going to walk through the guidelines for the STAR
app. By joining STAR, you agree to follow our guidelines when posting on
STAR message boards, in direct messages, and during phone calls with
STAR staff.*

*Our Guidelines are designed to make sure our participants and staff are
protected and are treated professionally and with respect. All in-app
messages, posts, and phone calls with staff are regularly reviewed by
the STAR team, and staff will remove any discussion post, comment, or
individual member who does not follow these guidelines. The full app
guidelines can be found in the Study information section of the STAR
app.*

**Guideline 1: Always Use Respectful Language** *Our team is committed
to making the STAR app a space where individuals feel comfortable, safe,
and empowered to communicate while supporting their recovery. Therefore,
STAR will not tolerate sexual harassment, hate speech, violent or vulgar
remarks, or hurtful language of any kind on app discussion boards or in
communications with STAR staff.*

**Guideline 2: Use a Professional communication style** *Please
communicate with staff and other STAR participants as you would in a
professional work setting. You may send direct messages to staff with
questions, comments, or concerns about the STAR study at any time.
However, all Direct Messages to staff should be on topic and
professional in tone. Similarly, posts and replies to topics on
discussion boards should remain on topic and maintain a professional
tone.*

*Our team is committed to responding to all messages from our
participants in a prompt and professional manner. In addition to the
standards outlined above, you can expect that any direct message or
phone call received by STAR staff to be responded to within 1 - 2
business days of the message being received. If you are ever reaching
out to report an issue with the STAR app, you will not be penalized for
study tasks missed while waiting for a response from study staff.*

**Guideline 3: Safe communication/privacy**

*Communications on the STAR app and with STAR staff are secure to
protect your privacy. Since posts and comments on message boards are
able to be viewed by other authorized STAR users, we request that all
users avoid sharing personal or private information that you would not
be willing to share with a total stranger. For example, you should never
share your full name, your phone number, your address, or your social
security number. While you are free to discuss details of your
participation in the study with people on other platforms, please be
mindful of the information you are sharing within the STAR app to make
sure that you are not accidentally sharing personal information about
someone else. If you would shred it, don't share it.*

**Review Process** *Our team keeps a record of all messages and posts
sent within the STAR app, as well as all phone and email conversations
with STAR staff outside of the app. These records are regularly reviewed
by our STAR team to make sure communication follows our stated
guidelines.*

*If a member of the STAR team detects language or behavior that does not
follow our guidelines, a private written warning will be sent to
individuals following their first offence. A second offence may result
in the person's account being removed from the app and withdrawal from
the STAR study.*

*Study staff will always be available to discuss decisions about
warnings or withdrawal. These guidelines are meant to serve as general
rules for the type of behavior that will result in a warning or possible
withdrawal from the STAR study. The STAR team reserves the right to
determine if a participant has behaved inappropriately.*




