# Daily Update Tutorial Script {#sec-video_tutorial_daily_update}


<center>(The purpose of this video tutorial is to walk participants through how to complete the Daily Update)</center>

 

*In this video we are going to walk-through how to complete a daily update. The daily update is a short survey that will be the same every day. It first asks if you have any use of opioids to report and then asks questions about your experiences and feelings in the last 24 hours and the upcoming week.*

*The daily update should take less than a minute to complete. You can complete the daily update at any time but we would like you to try to complete it at the same time everyday so that it is part of your routine and you don't forget to complete it. A great time to complete the daily update is in the morning as you are getting ready for the day.*

*Every day, you will get a notification to complete the daily update when you open the Star app. The daily update will be available at 5am Central Time and you will have until 5am the next day to complete it.*

*To complete the daily update, you simply click the "Daily Update" button on the homepage of the STAR app or click the "Take now" button on the daily update notification.*

*The daily update has some instructions on the first page. These describe what the questions will be about and describe what we mean when we ask about "using drugs for 'non-medical reasons'". When we ask about using drugs for non-medical reasons, we are asking about whether you have taken drugs to feel high or intoxicated, taken a drug that you weren't prescribed, taken more of a drug than you were prescribed, taken a drug more frequently than prescribed, or used a drug for reasons other than why it was prescribed. We are not asking about your use of prescribed medications for opioid use (for example through your Medication Assisted Treatment program) or pain medications that you have taken exactly as prescribed by your doctor. We are only interested in your use of medications or drugs for the non-medical reasons we just described. When you are ready to continue, tap the orange "Continue" button.*

*After this page of instructions, the questions will begin. The first question is the most important question that we ask you on any survey. This question asks you whether you have used any opioids for non-medical reasons that you haven't already reported in a previous daily update. So, for example, if you miss a few daily updates and you used opioids for non-medical reasons in that time, you should report those times in the next daily update you complete. Your answer to this question is protected by The Certificate of Confidentiality for this project. We will keep it completely confidential and not share this information with anyone. Answering yes or no to this question does not affect your participation or payment in any way either. You can continue to participate regardless if you use or do not use opioids at any time. For more information about privacy protections, please visit the STAR study website.*

*If you indicate "Yes" meaning that you have used opioids for non-medical reasons that you have not yet reported, the next question will ask about the dates and times of your use. You will see four options for different blocks of time for each date between when you started the study and when you are filling out the daily update. The first block of time on any given day is the very early morning, from midnight to just before 6 in the morning. The next block is the morning from 6 in the morning to just before noon. The third block is the afternoon and early evening, from noon to just before 6 at night. The last -block is the evening, from 6 at night to just before midnight. You should select the block of time and date for each occasion you have used opioids. If you used opioids more than once, select all the times when you used opioids. If you are reporting a slip that happened more than a few days ago, you can use the side arrows to find the right dates.*

*It is very important that we know when you have used opioids for non-medical reasons. The main goal of our projects is to help people trying to recover from opioid use. Knowing when people in our project have used will allow us to see what circumstances lead to the opioid use for people in recovery.*

*We understand that it can be hard to report opioid use, especially right after you use. So, you can report that you have used opioids for non-medical reasons at any time and whenever you feel comfortable reporting it. However, we ask that you try to report it as soon as possible so that you don't forget about it. If you are not sure whether you have already reported any specific time you used opioids for non-medical reasons, you should report it again. It's okay to report the same time slip twice. This is much better than missing a report of your use.*

*After you answer the question about your use of opioids for non-medical reasons, there will be two more sets of questions. The first set will include questions about the previous 24 hours. That is, the questions ask about your experiences and behaviors since the same time on the previous day. This will include questions about use of drugs other than opioids, medication use, urges, mood, and other experiences over the past 24 hours.*

*The final set of questions asks about the future rather than the past. You will be asked to think about your recovery over the next week. Specifically, you will be asked to rate how confident you are in your ability to completely avoid using opioids for non-medical reasons and how motivated you are to completely avoid using opioids for non-medical reasons.*

*After that you are done with the daily update. You will see a message that says, "Thank you! You have now completed the daily update."*

*You can only complete the daily update once a day.*

*You can earn up to \$33 per month for completing daily updates, paid to your study debit card. For every daily update you complete, you will earn a small payment (\$0.75 per daily update). If you complete at least 6 daily updates each week, you will earn the maximum payment of \$33 per month.*

*Try to complete a daily update every day and answer every question on the daily update. Completing the daily update is a very important aspect of your participation in this study. To continue participating in the study, you will have to complete at least 20 daily updates every month.*

*During the study, you might be in a situation where you can't complete the daily update, like if you lose your phone. If that happens, please email or call study staff as soon as you are able to let us know.*

*The STAR app will alert us if you are missing a lot of daily updates or not answering every question. If that happens, we will reach out to you to ask if everything is okay and to help you with any issues that you are having with the daily update.*
