# Daily Video Check-In Tutorial Script

NOTE: Video checkins were eliminated in early 2023. This script is therefore only kept as a historial record.

(The purpose of this video tutorial is to walk participants through how
to complete the Daily Video Check-In.)

**Script**

*In this video I am going to tell you how to complete a daily video
check-in.These videos are being collected to provide risk signals from
what you say, how you say it, and your facial expressions.*

*The daily video check-in is not a required study task, and your
participation will not be negatively affected if you decide not to do
any video check-ins.If you decide that you enjoy doing them, we will pay
you extra for each video check-in you complete.*

*The daily video check-in should take about one minute to complete. You
can complete the daily video check-in any time, but we would like you to
try to complete it about the same time every day so that it is part of
your routine, and you don't forget to complete it. A great time to
complete the daily video check-in is in the morning as you are getting
ready for your day.*

*In the STAR app you will get a notification to complete the daily video
check-in every day when you open the app. The daily video check-in will
be available at 5am Central Time and you will have until 5am the next
day to complete it.*

*To complete the daily video check-in, you simply click the "Daily Video
Check-In" button on the home page of the STAR app or click the "GO"
button on the daily video check-in notification.*

*When you open the daily video check-in, you will see the prompt and
instructions at the top of the page to help you record your video. The
prompt is, "Please find a quiet and private place to record yourself.
When you are ready, talk for up to a minute about a rose (a success or
positive event), a bud (an event you are looking forward to in the
future), or a thorn (a challenge or negative event)*

*Here are the steps that you should follow:*

*First, find a place that is mostly quiet and somewhere relatively quiet
where you feel comfortable sharing freely*

*Decide what you are going to share: a rose (something positive), a bud
(something positive in the future), or a thorn (something negative). You
can share anything that comes to mind in the moment. Your check-in can
be, related to your recovery or not, positive or negative, or a big
event or a small event.*

*Start recording by hitting the "Record Video" button.*

*Use the camera in selfie mode -- so that the camera is facing you.
There will be a button you can tap to switch to have the camera facing
you while you are still looking at the screen.*

*Look at the phone while you speak.*

*Start your video by saying what you are sharing:* *"My rose for today
is ..." ,* *"My thorn for today is ..." or* *"My bud for today is ..."*

*Then say what the rose, bud, or thorn is and explain why you chose it
and how it affects you.*

*Talk like you are talking to a friend.*

*Your check-in does not have to be long, but it can be if you would
like. For most people, it will take about 30 seconds*

*Stop recording by tapping the shutter button. Then, tap the checkmark
to submit it.*

*You'll see a message that says: "Successfully uploaded video."*

*We will sometimes check that you have recorded videos and that there
are no issues with them but we won't watch them in full or right away.
So, the video recording is not a way to talk to STAR staff or ask for
help. If you want to talk to STAR staff, visit the study information
tab.*

*Additionally, the videos will be stored on our secure server and will
be destroyed once we have analyzed the data at the end of the study.*

*Once again,you are not required to complete daily video check-in's.*

*For every daily video check-in you complete, you get 50 cents. That
means if you complete all daily video check ins, you'll get \$150 added
to your payment card each month.*