# Withdrawal/Discontinuation SOP

This SOP describes the steps study staff will take and the documentation required when a study participant withdraws consent, the principal investigator (PI) removes a participant from the study, or when the participant is lost to follow-up.

## Procedures

-	Tracking of participant removal, withdrawal, or lost to follow-up status is documented in the date_log_risk2, indicating the date the event occurred. 

-	In STAR - study staff must:

	-	Give the participant a *Study End Date*
	
	-	Turn off the *Has Private Messages Access* permission
	
	-	Turn off the *Has Discussion Group Access* permission (Only if participant was withdrawn for guideline violations)

## Withdrawal - Participants removed by the PI

-	The PI may remove a research participant from the study at any time in the event the participant's safety or the safety of staff may be compromised. The message sent to the participant will depend on the reason(s) for withdrawal.  The circumstances may involve:

	-	Low Compliance
	
	-	Violation of Study Guidelines 
	
-	Documentation, including the date of removal and rationale, must be entered in the Date Log. 

## Discontinue - Participant decides to end their participation

-	Study staff should request the participant provide a written communication to the PI indicating their decision to stop participation. 

	-	This information should be logged in date_log_risk2
	
-	The date of this communication will serve as the date of participant withdrawal unless the participant has already done so verbally.

-	If the participant indicates their withdrawal verbally and is unwilling to do so in writing, date_log_risk2 should reflect these circumstances. 

-	At the time of participant withdrawal, the research team should inquire about the participant's reason for withdrawal. 

## Participants lost to follow-up/non-responsive 

-	Five (5) contact attempts (through direct message/through email/through telephone) should be documented by study staff before considering the participant lost to follow-up: 

	-	At least one Direct Message
	
	-	At least one email 
	
	-	At least two text messages

	-	At least two phone calls
	
-	If study staff is unable to get a response, participant should be sent the Low Compliance withdrawal message 

## Ariela's quick checklist for taking people off study

- Mark the participant off study in STAR
  - Go to “User Admin” -> their subid
  - Set study end date for today
  - Under permissions, disable access to discussion boards and private messaging
- Submit a visit date log with the participant’s end date and relevant notes: https://uwmadison.co1.qualtrics.com/jfe/form/SV_2hPstJohCYbTmKi
- Indicate the withdrawal or discontinuation in the participant’s thread on Slack
- Submit payment, if owed, and log the payment in the payment log
- Send withdrawal or discontinuation notification via:
  - Email. Ensure latest email address by checking thread and STAR account. If no changes, use email address provided in enrollment database
  - Text.
  
The notification should read something like this, with relevant information input:

*[Name],*

*This is Dr. John Curtin from the STAR Study writing to notify you that, as of [today’s date and year] you are no longer a participant in the STAR study.*

*Our project requires that participants meet minimum study requirements. These requirements mean that study staff must remove participants who do not complete a sufficient number of surveys and/or share phone data. We have made the decision to end your participation as [insert reasoning].*

*Today, you received a final payment of [include payment and what for].*

*We have logged you out of the STAR App and are not collecting data from you. If you would like to continue using the app, please go to the Research Study Settings in your app and disable all data sharing.*

*Thank you for participating in our study. Please let us know if you have any questions about your discontinuation or the STAR study.*

*Take care,*

*Dr. John Curtin and the STAR Team*



